
def career_selection(career_name):

    career_dict = {'Agitator Advance Scheme': {
        'Statblock': [5, 5, 0, 0, 5, 10, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
        'Skills': ['Academic Knowledge (History) or Gossip', 'Academic Knowledge(Law) or Common Knowledge (the Empire)',
                  'Concealment', 'Charm', 'Perception', 'Read/Write', 'Speak Language (Breton or Tilean)',
                  'Speak Language (Reikspiel)'],
        'Talents': ['Coolheaded or Street Fighting', 'Flee!', 'Public Speaking'],
        'Trappings': ['Light Armour (Leather Jack)', 'One set of Good Craftsmanship Clothes',
                      '2d10 leaflets for various causes'],
        'Career Entries': ['Burgher', 'Captain', 'Herald', 'Highwayman', 'Scribe', 'Servant', 'Student', 'Zealot'],
        'Career Exits': ['Charlatan', 'Demagogue', 'Outlaw', 'Politician,Rogue, Zealot']},
        'Apprentice Wizard Advance Scheme': {
            'Statblock': [0, 0, 0, 0, 5, 10, 15, 5, 0, 2, 0, 0, 0, 1, 0, 0],
            'Skills': ['Academic Knowledge (Magic)', 'Channelling', 'Magical Sense', 'Perception', 'Read/Write',
                       'Search', 'Speak Arcane Language (Magick)', 'Speak Language (Classical)'],
            'Talents': ['Aethyric Attunement or Fast Hands', 'Petty Magic (Arcane)', 'Savvy or Very Resilient'],
            'Trappings': ['Quarter Staff', 'Backpack', 'Printed Book'],
            'Career Entries': ['Hedge Wizard', 'Scholar', 'Scribe', 'Student'],
            'Career Exits': ['Journeyman Wizard', 'Scholar', 'Scribe']},
        'Bailiff Advance Scheme': {
            'Statblock': [5, 5, 5, 0, 0, 10, 5, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Law)', 'Animal Care or Gossip', 'Charm', 'Command or Navigation',
                       'Intimidate or Common Knowledge (the Empire)', 'Perception', 'Read/Write', 'Ride'],
            'Talents': ['Etiquette or Super Numerate', 'Public Speaking'],
            'Trappings': ['Light Armour (Leather Jack and Leather Skullcap)', 'Riding Horse with Saddle and Harness',
                          'One Set of Good Craftsmanship Clothing'],
            'Career Entries': ['Bodyguard', 'Jailer'],
            'Career Exits': ['Militiaman', 'Politician', 'Protagonist', 'Racketeer', 'Smuggler', 'Toll Keeper']},
        'Barber-Surgeon Advance Scheme': {
            'Statblock': [5, 0, 0, 0, 10, 10, 10, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Drive or Swim', 'Haggle', 'Heal', 'Read/Write',
                       'Speak Language (Breton, Reikspiel, or Tilean)', 'Trade (Apothecary)'],
            'Talents': ['Resistance to Disease or Savvy', 'Suave or Very Resilient', 'Surgery'],
            'Trappings': ['Trade Tools (Barber-Surgeon)'],
            'Career Entries': ['Initiate', 'Student'],
            'Career Exits': ['Interrogator', 'Grave Robber', 'Tradesman', 'Vagabond']},
        'Boatman Advance Scheme': {
            'Statblock': [10, 5, 5, 5, 10, 5, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (The Empire or Kislev)', 'Consume Alcohol or Gossip', 'Navigation',
                       'Outdoor Survival', 'Perception', 'Row', 'Sail',
                       'Secret Language (Ranger) or Speak Language (Kislevian)', 'Swim'],
            'Talents': ['Orientation', 'Seasoned Traveller'],
            'Trappings': ['Light Armour (Leather Jack)', 'Row Boat'],
            'Career Entries': ['Ferryman', 'Smuggler'],
            'Career Exits': ['Fisherman', 'Marine', 'Navigator', 'Smuggler']},
        'Bodyguard Advance Scheme': {
            'Statblock': [10, 0, 5, 5, 5, 0, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Heal', 'Intimidate', 'Perception'],
            'Talents': ['Disarm or Quick Draw', 'Specialist Weapon Group (Parrying)',
                        'Specialist Weapon Group (Throwing)', 'Street Fighting', 'Strike to Stun',
                        'Very Strong or Very Resilient'],
            'Trappings': ['Buckler', 'Knuckle-dusters', 'A Pair of Throwing Axes or Throwing Knives',
                          'Light Armour (Leather Jack)'],
            'Career Entries': ['Estalian Diestro', 'Jailer', 'Mercenary', 'Thug'],
            'Career Exits': ['Bailiff', 'Bounty Hunter', 'Interrogator', 'Mercenary', 'Protagonist', 'Racketeer']},
        'Bone Picker Advance Scheme': {
            'Statblock': [5, 0, 5, 10, 5, 0, 5, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Charm or Gossip', 'Drive', 'Common Knowledge (the Empire)', 'Evaluate', 'Haggle',
                       'Search'],
            'Talents': ['Coolheaded or Streetwise', 'Hardy or Resistance to Disease'],
            'Trappings': ['Cart', '3 Sacks'],
            'Career Entries': ['Peasant', 'Rat Catcher', 'Vagabond'],
            'Career Exits': ['Camp Follower', 'Cat Burglar', 'Fence', 'Grave Robber', 'Smuggler']},
        'Bounty Hunter Advance Scheme': {
            'Statblock': [5, 10, 5, 0, 10, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Follow Trail', 'Intimidate', 'Outdoor Perception', 'Search', 'Shadowing', 'Silent Move'],
            'Talents': ['Marksman or Strike to Stun', 'Rover', 'Specialist Weapon Group (Entangling)',
                        'Sharpshooter or Strike Mighty Blow'],
            'Trappings': ['Crossbow with 10 bolts', 'Net', 'Light Armour (Leather Jerkin and Leather Skullcap)',
                          'Manacles', '10 Yards of Rope'],
            'Career Entries': ['Bodyguard', 'Fieldwarden', 'Kislevite Kossar', 'Mercenary', 'Pit Fighter'],
            'Career Exits': ['Mercenary', 'Protagonist', 'Scout', 'Vampire Hunter']},
        'Burgher Advance Scheme': {
            'Statblock': [5, 0, 0, 0, 5, 10, 5, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Empire) or Consume Alcohol', 'Drive', 'Evaluate', 'Gossip or Read/Write',
                       'Haggle', 'Perception', 'Search', 'Speak Language ( Kislevian', 'or Tilean)',
                       'Speak Language (Reikspiel)'],
            'Talents': ['Dealmaker', 'Savvy or Suave'],
            'Trappings': ['Abacus', 'Lantern', 'One Set of Good Clothing'],
            'Career Entries': ['Innkeeper', 'Servant'],
            'Career Exits': ['Agitator', 'Fence', 'Innkeeper', 'Militiaman', 'Tradesman', 'Valet']},
        'Camp Follower Advance Scheme': {
            'Statblock': [0, 0, 0, 5, 10, 5, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Drive', 'Charm or Gossip', 'Haggle', 'Perception', 'Search',
                       'Any one of: Trade (Armourer', 'Bowyer', 'Cartographer', 'Gunsmith', 'Herbalist', 'Merchant',
                       'Smith', 'Tailor', 'or Weaponsmith)', 'Speak Language (Breton', 'or Tilean)', 'Sleight of Hand'],
            'Talents': ['Dealmaker or Street Fighter', 'Flee!', 'Hardy or Resistance to Disease or Seasoned Traveller'],
            'Trappings': ['Lucky Charm or Trade Tools', 'Pouch', 'Tent'],
            'Career Entries': ['Bone Picker', 'Servant'],
            'Career Exits': ['Charcoal-Burner', 'Charlatan', 'Smuggler', 'Spy', 'Tradesman', 'Vagabond']},
        'Charcoal-Burner Advance Scheme': {
            'Statblock': [5, 0, 5, 5, 5, 5, 5, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Empire) or Drive or Gossip', 'Haggle', 'Outdoor Perception',
                       'Scale Sheer Surface', 'Search', 'Secret Signs (Ranger)'],
            'Trappings': ['3 Torches', 'Tinderbox', 'Hand Weapon (Hatchet)'],
            'Career Entries': ['Camp Follower', 'Hunter', 'Miner', 'Peasant'],
            'Career Exits': ['Hunter', 'Miner', 'Scout', 'Vagabond', 'Woodsman']},
        'Coachman Advance Scheme': {
            'Statblock': [5, 10, 0, 0, 10, 0, 5, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Drive', 'Gossip or Haggle', 'Heal or Navigation', 'Perception',
                       'Secret Signs (Ranger)', 'Speak Language (Breton', 'Kislevian', 'or Tilean)'],
            'Talents': ['Quick Draw or Seasoned Traveller', 'Specialist Weapon Group (Gunpowder)'],
            'Trappings': ['Blunderbuss with powder/ammunition enough for 10 shots',
                          'Medium Armour (Mail Shirt and Leather Jack)', 'Instrument (Coach Horn)'],
            'Career Entries': ['Outrider', 'Messenger'],
            'Career Exits': ['Ferryman', 'Highwayman', 'Outlaw', 'Scout', 'Smuggler', 'Toll Keeper']},
        'Entertainer Advance Scheme': {
            'Statblock': [5, 10, 0, 0, 10, 0, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Swim', 'Charm', 'Common Knowledge (the Empire)', 'Evaluate or Gossip',
                       'Perception', 'Performer (any two)', 'Speak Language (Reikspiel)', 'Any one of:',
                       'Animal Training', 'Blather', 'Charm Animal', 'Hypnotism', 'Ride', 'Scale Sheer Surface',
                       'Sleight of Hand', 'Ventriloquism'],
            'Talents': ['Any two of:', 'Contortionist', 'Lightning Reflexes', 'Public Speaking', 'Quick Draw',
                        'Sharpshooter', 'Specialist Weapon Group (Throwing)', 'Trick Riding', 'Very Wrestling'],
            'Trappings': ['Light Armour (Leather Jerkin)', 'Any one of: Instrument (any one)',
                          'Trade Tools (Performer)', '3 Throwing Knives', '2 Throwing Axes', 'Any one of: Costume',
                          'One Set of Good Craftsmanship Clothes'],
            'Career Entries': ['Herald', 'Rogue', 'Thief', 'Vagabond'],
            'Career Exits': ['Charlatan', 'Minstrel', 'Rogue', 'Thief', 'Vagabond']},
        'Envoy Advance Scheme': {
            'Statblock': [5, 5, 0, 0, 5, 10, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Common Knowledge (the Empire or the Wasteland)', 'Evaluate', 'Gossip', 'Haggle',
                       'Read/Write', 'Secret Language (Guild Tongue)', 'Trade (Merchant)'],
            'Talents': ['Dealmaker or Seasoned Traveller'],
            'Trappings': ['Light Armour (Leather Jack)', '2 sets of Good Craftsmanship Clothes', 'Writing Kit'],
            'Career Entries': ['Student', 'Tradesman'],
            'Career Exits': ['Charlatan', 'Merchant', 'Rogue', 'Seaman', 'Vagabond']},
        'Estalian Diestro Advance Scheme': {
            'Statblock': [15, 0, 5, 5, 10, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Science)', 'Common Knowledge (Estalia)', 'Dodge Blow',
                       'Read/ Speak Language (Estalian)'],
            'Talents': ['Lightning Reflexes or Quick Draw or Strike to Injure', 'Specialist Weapon Group (Fencing)',
                        'Strike Mighty Blow'],
            'Trappings': ['Foil or Rapier', 'One set of Best Craftsmanship Clothes', 'Perfume or Healing Draught'],
            'Career Entries': ['None'],
            'Career Exits': ['Bodyguard', 'Duellist', 'Protagonist', 'Rogue']},
        'Ferryman Advance Scheme': {
            'Statblock': [5, 5, 10, 5, 5, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Common Knowledge (the Empire)', 'Evaluate or Secret Language (Ranger Tongue)',
                       'Gossip orIntimidate', 'Haggle', 'Perception', 'Row', 'Swim'],
            'Talents': ['Marksman or Suave', 'Specialist Weapon Group (Gunpowder) or Street Fighting'],
            'Trappings': ['Crossbow with 10 bolts or Blunderbuss with powder/ammunition enough for 10 shots',
                          'LightArmour (Leather Jack)'],
            'Career Entries': ['Coachman', 'Smuggler', 'Toll Keeper'],
            'Career Exits': ['Boatman', 'Highwayman', 'Roadwarden', 'Smuggler']},
        'Fieldwarden Advance Scheme': {
            'Statblock': [5, 10, 0, 5, 10, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Necromancy) or Common Knowledge (the Empire)', 'Concealment',
                       'Follow Outdoor Survival', 'Perception', 'Search', 'Silent Move'],
            'Talents': ['Fleet Footed or Savvy', 'Mighty Shot or Rapid Reload', 'Rover or Quick Draw'],
            'Trappings': ['Sling with Ammunition', 'Lantern', 'Lamp Spade', 'Pony with Saddle and Harness'],
            'Career Entries': ['Hunter', 'Militiaman', 'Toll Keeper'],
            'Career Exits': ['Bounty Hunter', 'Mercenary', 'Scout', 'Vampire Hunter']},
        'Fisherman Advance Scheme': {
            'Statblock': [0, 5, 10, 5, 10, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Empire or the Wasteland)', 'Consume Alcohol or Haggle',
                       'Navigationor Trade (Merchant)', 'Outdoor Survival', 'Row', 'Sail',
                       'Speak Language (Reikspiel or Norse)', 'Swim'],
            'Talents': ['Hardy or Savvy', 'Orientation or Street Fighting'],
            'Trappings': ['Fish Hook and Line', 'Spear'],
            'Career Entries': ['Boatman', 'Peasant'],
            'Career Exits': ['Marine', 'Merchant', 'Navigator', 'Seaman']},
        'Grave Robber Advance Scheme': {
            'Statblock': [5, 5, 5, 0, 10, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Drive', 'Gossip or Haggle', 'Perception', 'Scale Sheer Surface', 'Search',
                       'Secret Signs (Thief)', 'Silent Move'],
            'Talents': ['Flee!', 'Resistance to Disease', 'Streetwise or Strongminded'],
            'Trappings': ['Lantern', 'Lamp Oil', 'Pick', 'Sack', 'Spade'],
            'Career Entries': ['Barber-Surgeon', 'Bone Picker', 'Rat Catcher'],
            'Career Exits': ['Cat Burglar', 'Fence', 'Rat Catcher', 'Thief']},
        'Hedge Wizard Advance Scheme': {
            'Statblock': [0, 0, 0, 5, 5, 5, 10, 10, 2, 0, 0, 0, 1, 0, 0],
            'Skills': ['Animal Care or Haggle', 'Charm or Channelling', 'Charm Animal or Trade (Apothecary)',
                       'Heal or Hypnotism', 'Magical Sense', 'Perception', 'Search'],
            'Talents': ['Hedge Magic', 'Petty Magic (Hedge)'],
            'Trappings': ['Healing Draught', 'Hood'],
            'Career Entries': ['None'],
            'Career Exits': ['Apprentice Wizard', 'Charlatan', 'Outlaw', 'Vagabond']},
        'Hunter Advance Scheme': {
            'Statblock': [0, 15, 0, 5, 10, 5, 0, 0, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Concealment', 'Follow Trail', 'Outdoor Perception', 'Search or Swim', 'Secret Signs (Ranger)',
                       'Silent Move or Set Trap'],
            'Talents': ['Hardy or Specialist Weapon Group (Longbow)', 'Lightning Reflexes or Very Resilient',
                        'Marksman or Rover', 'Rapid Reload'],
            'Trappings': ['Longbow with 10 arrows', '2 Animal Antitoxin Kit'],
            'Career Entries': ['Charcoal-Burner', 'Kithband Woodsman'],
            'Career Exits': ['Bounty Hunter', 'Charcoal- Fieldwarden', 'Kithband Warrior', 'Miner', 'Soldier',
                             'Targeteer']},
        'Initiate Advance Scheme': {
            'Statblock': [5, 5, 0, 5, 0, 10, 10, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Astronomy or History)', 'Academic Knowledge (Theology)', 'Charm', 'Heal',
                       'Perception', 'Read/Write', 'Speak Language (Classical)', 'Speak Language(Reikspiel)'],
            'Talents': ['Lightning Reflexes or Very Strong', 'Public Speaking', 'Suave or Warrior Born'],
            'Trappings': ['Religious Symbol (see Chapter 8,: Religion and Belief for types), Robes'],
            'Career Entries': ['Hedge Wizard', 'Knight', 'Scribe', 'Vampire Hunter', 'Witch Hunter', 'Zealot'],
            'Career Exits': ['Barber-Surgeon', 'Demagogue', 'Friar', 'Priest', 'Zealot']},
        'Jailer Advance Scheme': {
            'Statblock': [10, 0, 10, 10, 0, 0, 5, 0, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Command', 'Consume Alcohol', 'Dodge Blow', 'Heal or Sleight of Hand', 'Intimidate',
                       'Perception', 'Search'],
            'Talents': ['Resistance to Disease', 'Resistance to Specialist Weapon Group (Entangling)', 'Wrestling'],
            'Trappings': ['Bottle of Common Wine', 'Tankard', 'Any one of: Bola', 'Lasso', 'Net'],
            'Career Entries': ['Bodyguard', 'Rat Catcher'],
            'Career Exits': ['Bailiff', 'Bodyguard', 'Interrogator', 'Rat Watchman Kislevite']},
        'Kossar Advance Scheme': {
            'Statblock': [10, 10, 0, 10, 0, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (Kislev)', 'Consume Dodge Blow', 'Gamble or Gossip', 'Outdoor Perception',
                       'Search', 'Speak Language (Kislevian)'],
            'Talents': ['Specialist Weapon Group (Two-handed)', 'Strike to Injure'],
            'Trappings': ['Bow with 10 arrows', 'Great Weapon (Two-handed Axe)',
                          'Medium Armour (Mail Leather Jack and Leather Leggings)'],
            'Career Entries': ['None'],
            'Career Exits': ['Bounty Hunter', 'Mercenary', 'Shieldbreaker', 'Veteran']},
        'Kithband Warrior Advance Scheme': {
            'Statblock': [5, 5, 0, 0, 10, 10, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Concealment', 'Dodge Blow', 'Follow Trail', 'Heal or Search', 'Outdoor Survival', 'Perception',
                       'Scale SheerSurface', 'Silent Move'],
            'Talents': ['Marksman or Rover', 'Rapid Reload or Warrior Born'],
            'Trappings': ['Elfbow with 10 arrows', 'Light Armour (Leather Jack)'],
            'Career Entries': ['Hunter', 'Messenger'],
            'Career Exits': ['Hunter', 'Outrider', 'Vagabond', 'Veteran']},
        'Marine Advance Scheme': {
            'Statblock': [10, 10, 10, 0, 5, 0, 5, 0, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Wasteland) or Consume Alcohol', 'Dodge Blow',
                       'Gossip or Secret Language (Battle Tongue)', 'Intimidate', 'Row', 'Swim'],
            'Talents': ['Disarm or Quick Draw', 'Strike Mighty Strike to Stun'],
            'Trappings': ['Bow or Crossbow with 10 Arrows or Bolts', 'Light Armour (Leather Jack)', 'Shield',
                          'Grappling Hook', '10 Yards of Rope'],
            'Career Entries': ['Boatman', 'Fisherman', 'Seaman'],
            'Career Exits': ['Mate', 'Outlaw', 'Sergeant', 'Smuggler', 'Thug']},
        'Mercenary Advance Scheme': {
            'Statblock': [10, 10, 5, 5, 5, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Gamble', 'Common Knowledge ( Kislev', 'or Tilea)', 'Dodge Blow', 'Drive or Ride',
                       'Gossip or Haggle', 'Perception or Search', 'Secret Language (BattleTongue)',
                       'Speak Language (Tilean) or Swim'],
            'Talents': ['Disarm or Quick Draw', 'Rapid Reload or Strike Mighty Blow', 'Sharpshooter or Strike to Stun'],
            'Trappings': ['Crossbow with 10 Bolts', 'Shield', 'Medium Armour (Mail Shirt and Leather Jack)',
                          'Healing Draught'],
            'Career Entries': ['Bodyguard', 'Bounty Hunter', 'Fieldwarden', 'Kislevite Kossar', 'Militiaman',
                               'Norse Berserker', 'Outrider', 'Pit Fighter', 'Soldier', 'Watchman'],
            'Career Exits': ['Bodyguard', 'Bounty Hunter', 'Outlaw', 'Shieldbreaker', 'Veteran']},
        'Messenger Advance Scheme': {
            'Statblock': [5, 5, 0, 5, 10, 5, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Common Knowledge (the Empire or the Wasteland) or Gossip', 'Navigation',
                       'Outdoor Survival', 'Secret Signs (Scout)', 'Perception', 'Speak Language (Reikspiel)', 'Swim'],
            'Talents': ['Orientation', 'Seasoned Traveller'],
            'Trappings': ['Light Armour (Leather Jack)', 'Riding Horse with Saddle and Harness or Pony(for Halflings)',
                          'Map Case', 'Shield'],
            'Career Entries': ['Militiaman', 'Roadwarden', 'Servant'],
            'Career Exits': ['Coachman', 'Herald', 'Kithband Warrior', 'Outrider', 'Roadwarden', 'Scout', 'Soldier']},
        'Militiaman Advance Scheme': {
            'Statblock': [10, 5, 5, 5, 10, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Dodge Blow', 'Drive or Swim', 'Gamble or Gossip', 'Outdoor Survival',
                       'Perception', 'Search', 'Trade(any one)'],
            'Talents': ['Specialist Weapon Group (Two-handed) or Rapid Reload', 'Strike Mighty Blow'],
            'Career Entries': ['Artisan', 'Bailiff', 'Burgher', 'Merchant', 'Peasant', 'Tradesman', 'Woodsman'],
            'Trappings': ['Halberd or Bow with 10 arrows', 'Light Armour (Leather Jack and Leather Skullcap)',
                          'Uniform'],
            'Career Exits': ['Artisan', 'Fieldwarden', 'Mercenary', 'Outlaw', 'Sergeant', 'Thief']},
        'Miner Advance Scheme': {
            'Statblock': [5, 5, 10, 5, 0, 5, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Concealment or Evaluate or Outdoor Survival', 'Perception',
                       'Scale Sheer Surface', 'Trade (Miner or Prospector)'],
            'Talents': ['Orientation', 'Specialist Weapon Group (Two-handed)', 'Very Resilient or Warrior Born'],
            'Trappings': ['Great Weapon (Two-handed Pick)', 'Light Armour (Leather Jack)', 'Pick', 'Spade',
                          'Storm Lantern', 'Lamp Oil'],
            'Career Entries': ['Charcoal-Burner', 'Hunter'],
            'Career Exits': ['Charcoal-Burner', 'Engineer', 'Mercenary', 'Shieldbreaker', 'Smuggler']},
        'Noble Advance Scheme': {
            'Statblock': [10, 5, 0, 0, 5, 5, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Blather or Command', 'Common Knowledge (the Empire)', 'Consume Alcohol or Performer (Musician)',
                       'Charm', 'Gamble or Gossip', 'Read/Write', 'Ride', 'SpeakLanguage (Reikspiel)'],
            'Talents': ['Etiquette', 'Luck or Public Speaking', 'Savvy or Specialist Weapon (Fencing)',
                        'Schemer or SpecialistWeapon (Parrying)'],
            'Trappings': ['Foil', 'Main Gauche', 'Noble’s Garb', 'Riding Horse with Saddle and Harness', '1d10 gc',
                          'Jewellery worth 6d10 gc'],
            'Career Entries': ['Squire', 'Steward'],
            'Career Exits': ['Courtier', 'Pistolier', 'Politician', 'Rogue', 'Student']},
        'Norse Berserker Advance Scheme': {
            'Statblock': [15, 0, 10, 10, 0, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (Norsca)', 'Consume Intimidate', 'Performer (Storyteller)',
                       'Speak Language (Norse)', 'Swim'],
            'Talents': ['Frenzy', 'Menacing', 'Quick Draw', 'Specialist Weapon Group (Two-handed)'],
            'Trappings': ['Light Armour (Leather Jerkin)', 'Bottle of Great Weapon or Shield'],
            'Career Entries': ['None'],
            'Career Exits': ['Mercenary', 'Pit Fighter', 'Seaman', 'Veteran']},
        'Outlaw Advance Scheme': {
            'Statblock': [10, 10, 0, 0, 10, 5, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Common Knowledge (the Empire)', 'Concealment', 'Dodge Blow', 'Drive or Ride',
                       'Gossip or Secret Signs (Thief)', 'Perception', 'Scale Sheer Set Trap or Swim', 'Silent Move'],
            'Talents': ['Rover or Streetwise', 'Sharpshooter or Strike to Stun'],
            'Trappings': ['Bow with 10 arrows', 'Light Armour (Leather Jerkin)', 'Shield'],
            'Career Entries': ['Agitator', 'Charlatan', 'Coachman', 'Hedge Wizard', 'Innkeeper', 'Marine', 'Mercenary',
                               'Peasant', 'Roadwarden', 'Rogue', 'Squire', 'Toll Woodsman', 'Zealot'],
            'Career Exits': ['Demagogue', 'Highwayman', 'Thief', 'Veteran']},
        'Outrider Advance Scheme': {
            'Statblock': [5, 10, 0, 0, 10, 10, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Follow Trail', 'Outdoor Survival', 'Perception', 'Ride', 'Search',
                       'Silent Move'],
            'Talents': ['Coolheaded or Very Orientation', 'Specialist Weapon Group (Entangling)'],
            'Trappings': ['Bow or Crossbow with 10 arrows or Bolts', 'Net', 'Whip or Lasso',
                          'Light Armour(Leather Jack)', 'Shield', '10 Yards of Rope',
                          'Riding Horse with Saddle and Harness OR Pony(for Halflings)'],
            'Career Entries': ['Kithband Warrior', 'Roadwarden', 'Soldier'],
            'Career Exits': ['Coachman', 'Highwayman', 'Roadwarden', 'Scout']},
        'Peasant Advance Scheme': {
            'Statblock': [5, 5, 5, 10, 5, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Charm', 'Animal Training or Charm Animal or Trade (Cook)', 'Concealment',
                       'Drive or Trade (Bowyer)', 'Gamble or Performer (Dancer orSinger)',
                       'Outdoor Survival or Trade (Farmer)', 'Row orSet Trap', 'Scale Sheer Surface or Silent Move'],
            'Talents': ['Hardy or Rover', 'Flee! or Specialist Weapon Group (Sling)'],
            'Trappings': ['Sling or Quarter Staff', 'Leather Flask'],
            'Career Entries': ['None'],
            'Career Exits': ['Bone Picker', 'Charcoal-Burner', 'Militiaman', 'Outlaw', 'Politician', 'Servant',
                             'Zealot']},
        'Pit Fighter Advance Scheme': {
            'Statblock': [15, 0, 0, 10, 10, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Intimidate'],
            'Talents': ['Disarm or Wrestling', 'Quick Draw or Strike to Injure', 'Specialist Weapon Group (Flail)',
                        'SpecialistWeapon Group (Parrying)', 'Specialist Weapon Group(Two-handed)',
                        'Strike Mighty Blow', 'Very Strong orStrong-minded'],
            'Trappings': ['Flail or Great Weapon', 'Knuckle-duster', 'Shield or Buckler',
                          'Medium Armour (Mail Shirt and LeatherJack)'],
            'Career Entries': ['Norse Berserker', 'Protagonist', 'Thug'],
            'Career Exits': ['Bounty Hunter', 'Mercenary', 'Protagonist', 'Troll Slayer', 'Veteran']},
        'Protagonist Advance Scheme': {
            'Statblock': [10, 0, 10, 0, 10, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Gossip or Haggle', 'Intimidate', 'Ride'],
            'Talents': ['Disarm or Quick Draw', 'Menacing or Suave', 'Street Fighting', 'Strike Mighty Blow',
                        'Strike to Injure', 'Strike to Stun'],
            'Trappings': ['Medium Armour (Mail Shirt and Leather Jack)', 'Shield',
                          'Riding Horse with Saddle and Harness'],
            'Career Entries': ['Bailiff', 'Bodyguard', 'Bounty Hunter', 'Estalian Diestro', 'Pit Fighter'],
            'Career Exits': ['Duellist', 'Pit Fighter', 'Racketeer', 'Thief', 'Thug']},
        'Rat Catcher Advance Scheme': {
            'Statblock': [5, 10, 0, 5, 10, 0, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Animal Trainer', 'Perception', 'Search', 'Set Trap', 'Silent Move'],
            'Talents': ['Resistance to Disease', 'Resistance to Specialist Weapon Group (Sling)', 'Tunnel Rat'],
            'Trappings': ['Sling with Ammunition', '4 Animal Traps', 'Pole with 1d10 dead rats',
                          'Small but Vicious Dog'],
            'Career Entries': ['Grave Robber', 'Jailer', 'Runebearer', 'Tomb Robber'],
            'Career Exits': ['Bone Picker', 'Cat Burglar', 'Grave Jailer', 'Shieldbreaker', 'Thief']},
        'Roadwarden Advance Scheme': {
            'Statblock': [10, 10, 5, 0, 10, 5, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Common Knowledge (the Empire) or Gossip', 'Drive',
                       'Follow Trail or Secret Signs (Scout)', 'Navigation', 'Outdoor Survival', 'Perception', 'Ride',
                       'Search'],
            'Talents': ['Quick Draw or Rapid Reload', 'Specialist Weapons Group (Gunpowder)'],
            'Trappings': ['Pistol with 10 Firearm Balls and Medium Armour (Mail Shirt and Leather Jack)', 'Shield',
                          '10 Yards of Rope', 'Light Warhorse with Saddle and Harness (or Pony for Halfling)'],
            'Career Entries': ['Coachman', 'Ferryman', 'Outrider', 'Watchman'],
            'Career Exits': ['Highwayman', 'Messenger', 'Outlaw', 'Scout', 'Sergeant', 'Toll Keeper']},
        'Rogue Advance Scheme': {
            'Statblock': [5, 5, 0, 0, 10, 5, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Blather', 'Charm', 'Evaluate', 'Gamble or Secret Signs (Thief)', 'Gossip or Haggle',
                       'Perception', 'Performer(Actor or Storyteller)', 'Search or Secret Language(Thieves’ Tongue)',
                       'Speak Language (Reikspiel)'],
            'Talents': ['Flee! or Streetwise', 'Luck or Sixth Sense', 'Public Speaking'],
            'Trappings': ['One set of Best Craftsmanship Clothing or Dice or Deck of Cards', '1d10 gc'],
            'Career Entries': ['Agitator', 'Assassin', 'Duellist', 'Envoy', 'Estalian Diestro', 'Noble', 'Seaman',
                               'Thief', 'Valet'],
            'Career Exits': ['Charlatan', 'Demagogue', 'Entertainer', 'Servant', 'Thief']},
        'Runebearer Advance Scheme': {
            'Statblock': [10, 0, 5, 5, 10, 5, 5, 0, 2, 0, 0, 1, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Navigation', 'Outdoor Survival', 'Secret Signs (Scout)', 'Perception', 'Swim'],
            'Talents': ['Flee!', 'Fleet Footed or Sixth Sense', 'Rapid Reload', 'Very Resilient or Very Strong'],
            'Trappings': ['Crossbow and 10 Bolts', 'Light Armour (Leather Jerkin)', 'Healing Draught', 'Lucky Charm'],
            'Career Entries': ['Shieldbreaker'],
            'Career Exits': ['Rat Catcher', 'Scout', 'Shieldbreaker', 'Tomb Robber', 'Veteran']},
        'Scribe Advance Scheme': {
            'Statblock': [0, 0, 0, 0, 10, 10, 10, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (any one)', 'Common Knowledge (the Empire) or Gossip', 'Perception',
                       'Read/ Secret Language (Guild Tongue)', 'Speak Language(Breton)', 'Speak Language (Classical)',
                       'Speak Language(Reikspiel or Tilean)', 'Trade (Calligrapher)'],
            'Talents': ['Linguistics'],
            'Trappings': ['Knife', 'A Pair of Candles', 'Wax', '5 Illuminated Book', 'Writing Kit'],
            'Career Entries': ['Apprentice Wizard', 'Initiate'],
            'Career Exits': ['Agitator', 'Apprentice Wizard', 'Navigator', 'Scholar']},
        'Seaman Advance Scheme': {
            'Statblock': [10, 5, 10, 0, 10, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (Bretonnia', 'Tilea or the Wasteland)', 'Consume Alcohol or Perception',
                       'Dodge Blow', 'Row', 'Sail', 'Scale SheerSurface', 'Speak Language (Breton', 'Norse or Tilean)',
                       'Swim'],
            'Talents': ['Hardy or Street Fighting', 'Seasoned Traveller', 'Strike Mighty Blow or Swashbuckler'],
            'Trappings': ['Leather Jerkin', 'Bottle of Poor Craftsmanship Spirits'],
            'Career Entries': ['Boatman', 'Envoy', 'Ferryman', 'Norse Berserker', 'Smuggler'],
            'Career Exits': ['Marine', 'Mate', 'Navigator', 'Rogue', 'Smuggler']},
        'Servant Advance Scheme': {
            'Statblock': [5, 0, 5, 0, 10, 5, 10, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Trade (Cook)', 'Blather', 'Dodge Blow', 'Drive or Search', 'Evaluate or Haggle',
                       'Perception', 'Read/Write or Sleight of Hand'],
            'Talents': ['Acute Hearing or Flee!', 'Etiquette or Lightning Reflexes or Very Resilient'],
            'Trappings': ['One Set of Good Craftsmanship Clothing', 'Pewter Tankard', 'Tinderbox', 'Storm Lantern',
                          'Lamp Oil'],
            'Career Entries': ['Camp Follower', 'Peasant', 'Rogue'],
            'Career Exits': ['Agitator', 'Burgher', 'Camp Follower', 'Messenger', 'Spy', 'Thief', 'Valet']},
        'Shieldbreaker Advance Scheme': {
            'Statblock': [10, 0, 5, 5, 10, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Navigation', 'Perception', 'Scale Sheer Surface', 'Shadowing'],
            'Talents': ['Acute Hearing or Coolheaded', 'Strike Mighty Blow', 'Strike to Injure', 'Strike to Stun'],
            'Trappings': ['Crossbow with 10 bolts', 'Medium Armour (Mail Coat', 'Leather Jack and LeatherLeggings)',
                          'Shield', 'Grappling Hook', '10 Yards ofRope', 'Water Skin'],
            'Career Entries': ['Kislevite Kossar', 'Miner', 'Rat Catcher', 'Runebearer', 'Smuggler', 'Tomb Robber'],
            'Career Exits': ['Pit Fighter', 'Runebearer', 'Smuggler', 'Tomb Robber', 'Veteran']},
        'Smuggler Advance Scheme': {
            'Statblock': [5, 5, 0, 0, 10, 10, 0, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Drive', 'Evaluate', 'Gossip or Secret Language (Thieves’ Tongue)', 'Haggle', 'Perception',
                       'Row', 'Search', 'SilentMove', 'Speak Language (Breton or Kislevian) or Secret Signs (Thief)',
                       'Swim'],
            'Talents': ['Dealmaker or Streetwise'],
            'Trappings': ['Light Armour (Leather Jack)', '2 Torches', 'Draft Horse and Cart or Rowing Boat'],
            'Career Entries': ['Bailiff', 'Boatman', 'Bone Picker', 'Camp Follower', 'Coachman', 'Engineer', 'Ferryman',
                               'Marine', 'Miner', 'Seaman', 'Shieldbreaker'],
            'Career Exits': ['Boatman', 'Charlatan', 'Fence', 'Seaman', 'Shieldbreaker', 'Thief']},
        'Soldier Advance Scheme': {
            'Statblock': [10, 10, 0, 0, 10, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Heal', 'Common Knowledge (the Empire) or Perception', 'Dodge Blow',
                       'Drive or Gamble or Gossip', 'Intimidate'],
            'Talents': ['Disarm or Quick Draw', 'Sharpshooter or Strike Mighty Blow',
                        'Specialist Weapon Group (Gunpowderor Two-handed)',
                        'Strike to Injure or Rapid Strike to Stun or Mighty Shot'],
            'Trappings': ['Great Weapon (Halberd) or Firearm with ammunition for 10 shots', 'Shield',
                          'Light Armour (FullLeather Armour)', 'Uniform'],
            'Career Entries': ['Flagellant', 'Hunter', 'Messenger', 'Toll Watchman'],
            'Career Exits': ['Mercenary', 'Outrider', 'Sergeant', 'Veteran', 'Watchman']},
        'Squire Advance Scheme': {
            'Statblock': [10, 5, 5, 5, 5, 0, 0, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Genealogy/Heraldry) or Common Knowledge (Bretonnia)', 'Animal Care',
                       'Animal Training', 'Charm or Gossip', 'Dodge Ride', 'Speak Language (Breton or Reikspiel)'],
            'Talents': ['Etiquette', 'Specialist Weapon Group (Cavalry)', 'Strike Mighty Blow'],
            'Trappings': ['Demilance', 'Medium Armour (Mail Shirt', 'Mail Coif', 'Leather Jack)', 'Shield',
                          'Horse with Saddle and Harness'],
            'Career Entries': ['Herald', 'Noble', 'Valet'],
            'Career Exits': ['Knight', 'Noble', 'Outlaw', 'Sergeant', 'Veteran']},
        'Student Advance Scheme': {
            'Statblock': [0, 0, 0, 0, 10, 10, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (any one)', 'Academic Knowledge (any one) or Gossip',
                       'Charm or Consume Alcohol', 'Heal or Search', 'Perception', 'Read/Write',
                       'Speak Language (Classical)', 'Speak Language(Reikspiel)'],
            'Talents': ['Etiquette or Linguistics', 'Savvy or Suave', 'Seasoned Traveller or Super Numerate'],
            'Trappings': ['Two Textbooks corresponding to Knowledge Skills', 'Writing Kit'],
            'Career Entries': ['Envoy', 'Grave Robber', 'Minstrel', 'Valet'],
            'Career Exits': ['Agitator', 'Apprentice Wizard', 'Barber- Surgeon', 'Engineer', 'Envoy', 'Initiate',
                             'Physician', 'Scholar']},
        'Thief Advance Scheme': {
            'Statblock': [5, 5, 0, 0, 15, 5, 0, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm or Scale Sheer Surface', 'Evaluate or Disguise', 'Gamble or Pick Lock',
                       'Read/Write or Sleight of Hand', 'Search',
                       'Secret Language (Thieves’ Tongue) or Secret Signs (Thief)', 'Silent Move'],
            'Talents': ['Alley Cat or Streetwise', 'Super Numerate or Trapfinder'],
            'Trappings': ['Light Armour (Leather Jerkin)', 'Sack', 'Lock picks', '10 Yards of Rope'],
            'Career Entries': ['Entertainer', 'Grave Interrogator', 'Militiaman', 'Outlaw', 'Rat Catcher', 'Rogue',
                               'Servant', 'Smuggler', 'Toll Keeper', 'Tomb Robber', 'Vagabond'],
            'Career Exits': ['Cat Burglar', 'Entertainer', 'Fence', 'Rogue', 'Tomb Robber']},
        'Thug Advance Scheme': {
            'Statblock': [10, 0, 5, 5, 0, 0, 5, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Consume Alcohol', 'Dodge Blow', 'Gamble', 'Secret Language (Thieves’ Tongue)'],
            'Talents': ['Coolheaded or Lightning Reflexes', 'Resistance to Poison or Quick Draw',
                        'Strike to Injure or Wrestling', 'Strike to Stun'],
            'Trappings': ['Knuckle-dusters', 'Medium Armour (Mail Shirt and Leather Jerkin)'],
            'Career Entries': ['Marine', 'Protagonist'],
            'Career Exits': ['Bodyguard', 'Interrogator', 'Mercenary', 'Pit Fighter', 'RacketeerToll']},
        'Toll Keeper Advance Scheme': {
            'Statblock': [10, 5, 5, 10, 5, 0, 5, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Evaluate', 'Gossip or Haggle', 'Read/Write', 'Search', 'Speak Language(Kislevian',
                       'or Tilean)'],
            'Talents': ['Lightning Reflexes or Marksman'],
            'Trappings': ['Chest', 'Crossbow with 10 Bolts', 'Medium Armour (Mail Shirt and Leather Jerkin)', 'Shield',
                          '1d10 gc'],
            'Career Entries': ['Bailiff', 'Coachman', 'Roadwarden'],
            'Career Exits': ['Ferryman', 'Fieldwarden', 'Highwayman', 'Soldier', 'Politician', 'Thief']},
        'Tomb Robber Advance Scheme': {
            'Statblock': [10, 0, 0, 0, 10, 10, 10, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Empire) or Secret Signs (Thief)', 'Concealment or Outdoor Survival',
                       'Perception', 'Pick Lock or Silent Move', 'Read/ Scale Sheer Surface', 'Search',
                       'Speak Language ( Khazalid or Eltharin)'],
            'Talents': ['Luck or Sixth Sense', 'Trapfinder or Tunnel Rat'],
            'Trappings': ['Light Armour (Leather Jack)', 'Crowbar', 'Lamp Oil', '10 Yards of Rope', '2 Sacks'],
            'Career Entries': ['Runebearer', 'Shieldbreaker', 'Thief'],
            'Career Exits': ['Fence', 'Rat Catcher', 'Shieldbreaker', 'Vampire Hunter']},
        'Tradesman Advance Scheme': {
            'Statblock': [0, 0, 5, 5, 10, 5, 10, 0, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care or Gossip', 'Drive', 'Haggle', 'Perception', 'Read/Write',
                       'Secret Language (Guild Tongue)', 'Trade (any two)'],
            'Talents': ['Dealmaker or Savvy'],
            'Trappings': ['Light Armour (Leather Jerkin)', '1d10 gc'],
            'Career Entries': ['Barber-Surgeon', 'Burgher', 'Camp Peasant', 'Watchman'],
            'Career Exits': ['Artisan', 'Engineer', 'Envoy', 'Militiaman', 'Zealot']},
        'Troll Slayer Advance Scheme': {
            'Statblock': [10, 0, 5, 5, 5, 0, 10, 0, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Consume Alcohol', 'Dodge Blow', 'Intimidate'],
            'Talents': ['Disarm or Quick Draw', 'Hardy', 'Lightning Reflexes or Very Resilient',
                        'Specialist Weapon Group (Two-handed)', 'Street Fighter', 'Strike Mighty Blow'],
            'Trappings': ['Great Weapon', 'Light Armour (Leather Jerkin)', 'One Bottle of Poor Craftsmanship Spirits'],
            'Career Entries': ['Pit Fighter'],
            'Career Exits': ['Giant Slayer']},
        'Vagabond Advance Scheme': {
            'Statblock': [5, 10, 0, 0, 10, 5, 0, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (Bretonnia', 'Estalia', 'Kislev', 'or Tilea)',
                       'Gossip or Secret Language (Ranger Tongue orThieves’ Tongue)', 'Haggle or Swim',
                       'Heal or Navigation', 'Outdoor Survival', 'Performer ( Singer or Storyteller) or Secret Signs '
                                                                 '(Ranger or Thief)', 'Silent Move'],
            'Talents': ['Fleet Footed or Rover', 'Marksman or Seasoned Traveller'],
            'Trappings': ['Back Pack', 'Rations (1 week)', 'Tent', 'Water Skin'],
            'Career Entries': ['Barber-Surgeon', 'Camp Follower', 'Cat Charcoal-Burner', 'Entertainer', 'Envoy',
                               'Fieldwarden', 'Hedge Wizard', 'Kithband Warrior', 'Outlaw', 'Soldier', 'Woodsman'],
            'Career Exits': ['Bone Picker', 'Entertainer', 'Friar', 'Scout', 'Woodsman']},
        'Valet Advance Scheme': {
            'Statblock': [0, 0, 0, 0, 10, 10, 5, 10, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Genealogy/Heraldry)', 'Evaluate',
                       'Gossip or Speak Language (Breton or Reikspiel)', 'Haggle', 'Perception', 'Read/Write',
                       'Search'],
            'Talents': ['Coolheaded or Suave', 'Dealmaker or Seasoned Traveller', 'Etiquette'],
            'Trappings': ['Cologne', 'Purse', 'Two sets of Best Craftsmanship Clothing', 'Uniform'],
            'Career Entries': ['Burgher', 'Servant'],
            'Career Exits': ['Herald', 'Rogue', 'Squire', 'Steward', 'Student']},
        'Watchman Advance Scheme': {
            'Statblock': [10, 5, 5, 0, 5, 10, 0, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Law)', 'Dodge Blow', 'Follow Trail', 'Gossip', 'Intimidate', 'Perception',
                       'Search'],
            'Talents': ['Coolheaded or Savvy', 'Disarm or Street Strike Mighty Blow', 'Strike to Stun'],
            'Trappings': ['Light Armour (Leather Jack)', 'Lantern and Lamp Oil', 'Uniform'],
            'Career Entries': ['Jailer', 'Soldier'],
            'Career Exits': ['Mercenary', 'Racketeer', 'Sergeant', 'Soldier', 'Tradesman']},
        'Woodsman Advance Scheme': {
            'Statblock': [10, 0, 10, 0, 5, 0, 10, 0, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Concealment', 'Follow Trail or Set Perception', 'Scale Sheer Surface',
                       'Secret Language (Ranger Tongue)', 'Secret Signs (Ranger)', 'Silent Move'],
            'Talents': ['Fleet Footed or Very Resilient', 'Rover', 'Specialist Weapon Group (Two-handed)'],
            'Trappings': ['Great Weapon (Two-handed Axe)', 'Light Armour (Leather Jack)', 'Antitoxin Kit'],
            'Career Entries': ['Charcoal-Burner', 'Vagabond'],
            'Career Exits': ['Hunter', 'Militiaman', 'Outlaw', 'Vagabond']},
        'Zealot Advance Scheme': {
            'Statblock': [10, 0, 5, 10, 0, 0, 10, 5, 2, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Theology)', 'Charm', 'Common Knowledge (the Empire)', 'Intimidate',
                       'Read/Write'],
            'Talents': ['Coolheaded or Very Strong', 'Hardy or Public Speaking', 'Specialist Weapon Group (Flail)'],
            'Trappings': ['Flail or Morning Star', 'Light Armour (Leather Jack)',
                          'Bottle of Good Craftsmanship Spirits'],
            'Career Entries': ['Agitator', 'Initiate', 'Judicial Peasant', 'Tradesman'],
            'Career Exits': ['Agitator', 'Initiate', 'Flagellant', 'Friar', 'Outlaw']},
        'Anointed Priest Advance Scheme': {
            'Statblock': [15, 15, 10, 10, 10, 15, 25, 20, 5, 0, 0, 0, 2, 0, 0],
            'Skills': ['Academic Knowledge (any two)', 'Academic Knowledge (Theology)', 'Channelling', 'Charm',
                       'CommonKnowledge (any two)', 'Gossip', 'Heal', 'Magical Ride or Swim',
                       'Speak Arcane Language (Magick)', 'Speak Language (any two)'],
            'Talents': ['Aethyric Attunement or Meditation', 'Armoured Casting or Fast Hands', 'Divine Lore (any one)',
                        'LesserMagic (any two)', 'Seasoned Traveller or Strike MightyBlow'],
            'Trappings': ['Noble’s Garb'],
            'Career Entries': ['Priest'],
            'Career Exits': ['Demagogue', 'Flagellant', 'High Priest', 'Witch Hunter']},
        'Artisan Advance Scheme': {
            'Statblock': [0, 0, 10, 10, 20, 10, 10, 10, 3, 0, 0, 0, 0, 0, 0],
            'Skills': ['Drive', 'Evaluate', 'Gossip', 'Haggle', 'Perception', 'Secret Language (Guild Tongue)',
                       'Speak Language ( Breton', 'or Tilean)', 'Trade (any three)'],
            'Talents': ['Artistic or Etiquette'],
            'Trappings': ['Trade Tools (according to Trade)', '15 gc'],
            'Career Entries': ['Engineer', 'Militiaman', 'Navigator', 'Tradesman'],
            'Career Exits': ['Demagogue', 'Engineer', 'Guild Merchant', 'Militiaman']},
        'Assassin Advance Scheme': {
            'Statblock': [25, 25, 10, 10, 30, 20, 10, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Concealment', 'Disguise', 'Gossip', 'Perception', 'Prepare Poison', 'Scale Sheer Surface',
                       'Secret Signs (Thief)', 'Shadowing', 'Silent Move'],
            'Talents': ['Quick Draw', 'Lightning Parry', 'Sharpshooter', 'Specialist Weapon Group (Entangling)',
                        'Specialist Weapon Group(Parrying)', 'Specialist Weapon Group (Throwing)', 'StreetFighting',
                        'Streetwise', 'Swashbuckler'],
            'Trappings': ['Net', '4 Throwing Knives', 'Grappling 10 Yards of Rope', '1 dose of Poison (any)'],
            'Career Entries': ['Champion', 'Duellist', 'Judicial Champion', 'Outlaw Chief', 'Spy', 'Targeteer'],
            'Career Exits': ['Champion', 'Outlaw', 'Rogue', 'Sergeant', 'Witch Hunter']},
        'Captain Advance Scheme': {
            'Statblock': [30, 20, 20, 20, 20, 15, 15, 25, 7, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Strategy/ Tactics)', 'Animal Care', 'Common Knowledge (any three)',
                       'DodgeBlow', 'Gossip', 'Read/Write', 'Ride', 'SecretLanguage (Battle Tongue)',
                       'Speak Language(Kislevian or Tilean)'],
            'Talents': ['Disarm or Quick Draw', 'Lightning Specialist Weapon Group (Cavalry or Two-handed Weapon)',
                        'Specialist Weapon Group (Flail or Parrying)'],
            'Trappings': ['Flail or Sword-breaker', 'Lance or Great Weapon', 'Medium Armour (Full Mail Armour)',
                          'Shield',
                          'Destrier with Saddle andHarness', 'Unit of Troops'],
            'Career Entries': ['Explorer', 'Ghost Strider', 'Knight', 'Knight of the Inner Circle', 'Noble Lord',
                               'Outlaw Chief', 'Sergeant', 'Witch Hunter'],
            'Career Exits': ['Agitator', 'Explorer', 'Merchant', 'Outlaw', 'Politician']},
        'Cat Burglar Advance Scheme': {
            'Statblock': [10, 10, 5, 5, 25, 10, 10, 0, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Concealment', 'Evaluate', 'Gossip', 'Haggle', 'Pick Lock', 'Scale Sheer Surface', 'Search',
                       'Secret Language (Thieves’ Tongue)', 'Secret Signs (Thief)', 'Silent Move'],
            'Talents': ['Alley Cat', 'Street Fighting', 'Streetwise', 'Trapfinder'],
            'Trappings': ['Grappling Hook', 'Lock Picks', '10 Yards of Rope'],
            'Career Entries': ['Bone Picker', 'Charlatan', 'Grave Rat Catcher', 'Thief'],
            'Career Exits': ['Crime Lord', 'Fence', 'Master Thief', 'Vagabond']},
        'Champion Advance Scheme': {
            'Statblock': [40, 40, 25, 25, 30, 0, 20, 0, 8, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Evaluate', 'Intimidate', 'Perception'],
            'Talents': ['Fleet Footed or Lightning Reflexes', 'Lightning Parry', 'Master Gunner', 'Mighty Shot',
                        'Quick Rapid Reload', 'Specialist Weapon Group (any three)', 'Wrestling'],
            'Trappings': ['Any Six Weapons (all of Best Craftsmanship)', 'Medium Armour (Mail Shirt and Leather Jack)'],
            'Career Entries': ['Assassin', 'Duellist', 'Judicial Knight of the Inner Circle', 'Targeteer', 'Veteran',
                               'Witch Hunter'],
            'Career Exits': ['Assassin', 'Scout', 'Sergeant', 'Witch Hunter']},
        'Charlatan Advance Scheme': {
            'Statblock': [10, 10, 5, 10, 15, 15, 15, 25, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Blather', 'Charm', 'Common Knowledge (Bretonnia or Tilea)', 'Disguise', 'Evaluate', 'Gamble',
                       'Gossip', 'Perception', 'Secret Language (Thieves’ Tongue)', 'Sleightof Hand',
                       'Speak Language (Breton or Tilean)', 'SpeakLanguage (Reikspiel)'],
            'Talents': ['Flee!', 'Mimic', 'Public Speaking', 'Schemer or Seasoned Traveller'],
            'Trappings': ['6 sets of Common Clothes', '4 sets of Best Craftsmanship Clothes', 'Forged Document',
                          '4 bottles of variously coloured water', '4 bottles of variously coloured powder'],
            'Career Entries': ['Agitator', 'Camp Follower', 'Courtier', 'Envoy', 'Fence', 'Hedge Wizard',
                               'Journeyman Minstrel', 'Rogue', 'Smuggler', 'Thief'],
            'Career Exits': ['Cat Burglar', 'Demagogue', 'Outlaw', 'Politician', 'Spy']},
        'Coutier Advance Scheme': {
            'Statblock': [5, 5, 0, 0, 10, 20, 20, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (the Arts or History) or Gamble', 'Blather', 'Charm',
                       'Command or Performer(any one)', 'Common Knowledge (Bretonnia or Tilea)', 'Evaluate', 'Gossip',
                       'Perception', 'Read/Write', 'Speak Language (Breton or Tilean)', 'Speak Language(Reikspiel)'],
            'Talents': ['Dealmaker or Etiquette', 'Public Speaking', 'Savvy or Suave',
                        'Schemer or Specialist Weapon Group (Fencing)'],
            'Trappings': ['4 Sets of Noble’s Garb', '100 gc', 'Valet'],
            'Career Entries': ['Noble', 'Herald', 'Pistolier', 'Politician'],
            'Career Exits': ['Charlatan', 'Duellist', 'Noble Politician', 'Steward', 'Spy']},
        'Daemon Slayer Advance Scheme': {
            'Statblock': [40, 0, 30, 30, 20, 0, 30, 0, 8, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (any two)', 'Consume Alcohol', 'Dodge Blow', 'Intimidate',
                       'Scale SheerSurface'],
            'Talents': ['Lightning Parry', 'Unsettling'],
            'Trappings': ['Great Weapon'],
            'Career Entries': ['Giant Slayer'],
            'Career Exits': ['Glorious death']},
        'Demagogue Advance Scheme': {
            'Statblock': [10, 10, 0, 10, 15, 20, 15, 30, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (History)', 'Academic Knowledge (Law)', 'Blather', 'Charm', 'Command',
                       'Common Knowledge(the Empire)', 'Concealment', 'Disguise', 'Dodge Blow', 'Intimidate',
                       'Perception', 'Speak Language (Reikspiel)'],
            'Talents': ['Etiquette or Streetwise', 'Master Orator', 'Public Speaking', 'Street Fighting'],
            'Trappings': ['Light Armour (Leather Jack and Leather Skullcap)'],
            'Career Entries': ['Agitator', 'Anointed Priest', 'Artisan', 'Crime Lord', 'Flagellant', 'Friar',
                               'Initiate', 'Minstrel', 'Outlaw Chief', 'Politician', 'Rogue', 'Vampire Witch Hunter'],
            'Career Exits': ['Crime Lord', 'Friar', 'Mercenary', 'Outlaw', 'Politician']},
        'Duellist Advance Scheme': {
            'Statblock': [20, 20, 10, 20, 20, 15, 15, 10, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Dodge Blow', 'Gamble', 'Gossip', 'Perception', 'Sleight of Hand'],
            'Talents': ['Ambidextrous or Disarm', 'Etiquette', 'Master Mighty Shot', 'Quick Draw', 'Sharpshooter',
                        'Specialist Weapon Group (Fencing)', 'Specialist Weapon Group(Gunpowder)',
                        'Specialist Weapon Group (Parrying)', 'Strike Mighty Blow', 'Strike to Injure', 'Swashbuckler'],
            'Trappings': ['Main Gauche', 'Pistol with Powder and Ammunition for 10 Shots', 'Rapier'],
            'Career Entries': ['Courtier', 'Estalian Diestro', 'Pistolier', 'Protagonist', 'Sergeant', 'Targeteer'],
            'Career Exits': ['Assassin', 'Champion', 'Highwayman', 'Sergeant']},
        'Engineer Advance Scheme': {
            'Statblock': [10, 15, 5, 5, 10, 20, 10, 0, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Engineering)', 'Academic Knowledge (Science)',
                       'Common Knowledge (Dwarfs or Tilea)', 'Drive or Ride', 'Perception', 'Read/Write',
                       'SpeakLanguage (Khazalid or Tilean)', 'Trade (Gunsmith)'],
            'Talents': ['Master Gunner', 'Specialist Weapon Group (Engineer or Gunpowder)'],
            'Trappings': ['Light Armour (Leather Jack)', 'Engineer’s Kit', '6 Spikes'],
            'Career Entries': ['Artisan', 'Miner', 'Student', 'Tradesman'],
            'Career Exits': ['Artisan', 'Explorer', 'Guild Master', 'Smuggler']},
        'Explorer Advance Scheme': {
            'Statblock': [20, 20, 10, 15, 15, 25, 20, 15, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (History or Law)', 'Common Knowledge (any three)', 'Drive', 'Follow Trail', 
                       'Navigation', 'Outdoor Survival', 'Read/Write', 'Ride', 'Scale Sheer Surface', 
                       'Secret Language (Ranger Tongue)', 'Secret Signs (Scout)', 'Speak Language(any three)', 'Swim', 
                       'Trade (Cartographer)'],
            'Talents': ['Orientation or Linguistics', 'Seasoned Traveller'],
            'Trappings': ['Bow or Crossbow with 10 arrows or bolts', 'Hand Weapon', 
                          'Medium Armour (Mail Shirt and Leather Jack)', 'Shield', '6 Maps', 
                          '1,000 gc in coin and trade goods', 'Riding Horse with saddle and harness'],
            'Career Entries': ['Captain', 'Engineer', 'Herald', 'Master Master Wizard', 'Mate', 'Navigator', 'Scholar',
                               'Scout', 'Sea Captain', 'Spy', 'Wizard Lord'],
            'Career Exits': ['Captain', 'Merchant', 'Sea Captain', 'Spy']},
        'Fence Advance Scheme': {
            'Statblock': [15, 10, 10, 5, 10, 5, 10, 10, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Evaluate', 'Gamble', 'Gossip', 'Haggle', 'Perception', 'Sleight of Hand'],
            'Talents': ['Dealmaker or Streetwise', 'Strike to Stun', 'Super Numerate'],
            'Trappings': ['Trade Tools (Engraver’s Kit)', 'Writing Kit'],
            'Career Entries': ['Bone Picker', 'Burgher', 'Cat Burglar', 'Grave Robber', 'Innkeeper', 'Racketeer',
                               'Smuggler', 'Thief', 'Tomb Robber'],
            'Career Exits': ['Charlatan', 'Crime Lord', 'Master Thief', 'Racketeer']},
        'Flagellant Advance Scheme': {
            'Statblock': [15, 0, 10, 15, 5, 0, 20, 10, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Theology)', 'Charm', 'Intimidate', 'Speak Language (Classical)'],
            'Talents': ['Fearless', 'Specialist Weapon Group (Flail or Two-handed Weapon)', 'Strike Mighty Blow'],
            'Trappings': ['Flail or Great Weapon', 'Bottle of Good Craftsmanship Spirits', 'Religious Symbol', 
                          'Religious Relic'],
            'Career Entries': ['Anointed Priest', 'Friar', 'Priest', 'Zealot'],
            'Career Exits': ['Demagogue', 'Interrogator', 'Priest', 'Veteran']},
        'Friar Advance Scheme': {
            'Statblock': [10, 0, 5, 10, 0, 15, 15, 15, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Theology)', 'Animal Care', 'Common Knowledge (any two)', 'Outdoor Survival',
                       'Perception', 'Speak Language(Breton', 'Estalian', 'Kislevian', 'or Tilean)',
                       'SpeakLanguage (Classical)', 'Speak Language (Reikspiel)'],
            'Talents': ['Seasoned Traveller'],
            'Trappings': ['Healing Draught', 'Religious Religious Relic', 'Robes'],
            'Career Entries': ['Demagogue', 'Initiate', 'Physician', 'Vagabond', 'Zealot'],
            'Career Exits': ['Demagogue', 'Flagellant', 'Priest', 'Scholar']},
        'Ghost Strider Advance Scheme': {
            'Statblock': [20, 30, 15, 15, 25, 20, 20, 0, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Concealment', 'Dodge Blow', 'Follow Intimidate', 'Lip Reading', 'Navigation',
                       'Outdoor Survival', 'Perception', 'Secret Language (RangerTongue)', 'Secret Signs (Ranger)',
                       'Set Shadowing', 'Silent Move'],
            'Talents': ['Hardy or Fleet Footed', 'Lightning Parry', 'Mighty Shot', 'Quick Draw', 'RapidReload',
                        'Sure Shot'],
            'Trappings': ['Elfbow with 10 arrows', 'Light Armour (Best Craftsmanship Full LeatherArmour)'],
            'Career Entries': ['Scout'],
            'Career Exits': ['Captain', 'Outlaw Chief', 'Targeteer', 'Vampire Hunter']},
        'Giant Slayer Advance Scheme': {
            'Statblock': [25, 0, 15, 15, 10, 0, 20, 0, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (any one)', 'Consume Dodge Blow', 'Intimidate', 'Perception'],
            'Talents': ['Fearless', 'Resistance to Poison', 'Specialist Weapon Group (Flail)', 'Strike to Injure'],
            'Trappings': ['Great Weapon'],
            'Career Entries': ['Troll Slayer'],
            'Career Exits': ['Daemon Slayer']},
        'Guild Master Advance Scheme': {
            'Statblock': [10, 10, 0, 10, 15, 30, 20, 35, 5, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (History)', 'Charm', 'Common Knowledge (the Empire)', 'Evaluate', 'Haggle', 
                       'Perception', 'Secret Language (Guild Tongue)', 'Speak Language (Breton, Estalian, Kislevian, or'
                                                                       ' Norse)', 'Speak Language (Reikspiel)', 
                       'Trade (any two)'],
            'Talents': ['Dealmaker', 'Etiquette', 'Linguistics'],
            'Trappings': ['Writing Kit', '100 gc', 'Guild'],
            'Career Entries': ['Artisan', 'Engineer', 'Merchant', 'Wizard Lord'],
            'Career Exits': ['Crime Lord', 'Politician', 'Racketeer']},
        'Herald Advance Scheme': {
            'Statblock': [10, 10, 5, 5, 15, 15, 10, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Genealogy/Heraldry)', 'Academic Knowledge (History)', 'Blather', 'Charm',
                       'CommonKnowledge (Bretonnia', 'Kislev', 'or Tilea)', 'CommonKnowledge (the Empire)', 'Evaluate',
                       'Gossip', 'Perception', 'Read/Write', 'Ride', 'Speak Language(Breton', 'Kislevian', 'or Tilean)',
                       'Speak Language(Reikspiel)'],
            'Talents': ['Etiquette', 'Master Orator', 'Public Speaking'],
            'Trappings': ['Cologne', 'Purse', 'Two sets of Best Craftsmanship Clothing', 'Uniform'],
            'Career Entries': ['Messenger', 'Valet'],
            'Career Exits': ['Agitator', 'Courtier', 'Entertainer', 'Politician', 'Squire']},
        'High Priest Advance Scheme': {
            'Statblock': [20, 20, 15, 15, 15, 20, 30, 25, 6, 0, 0, 0, 3, 0, 0],
            'Skills': ['Academic Knowledge (any three)', 'Academic Knowledge (Theology)', 'Channelling', 
                       'Common Knowledge (any two)', 'Gossip', 'Intimidate', 'Magical Sense', 'Ride or Swim', 
                       'Speak Arcane Language (Magick)', 'Speak Language (anythree)'],
            'Talents': ['Aethyric Attunement or Meditation', 'Armoured Casting or Mighty Missile', 'Etiquette', 
                        'Fast Hands orStrong-minded', 'Lesser Magic (any two)'],
            'Trappings': ['Religious Relic'],
            'Career Entries': ['Anointed Priest'],
            'Career Exits': ['Politician', 'Scholar', 'Witch Hunter']},
        'Highwayman Advance Scheme': {
            'Statblock': [20, 20, 10, 10, 30, 20, 15, 25, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Animal Training', 'Common Knowledge (the Empire)', 'Gossip', 'Ride', 
                       'Silent Move'],
            'Talents': ['Ambidextrous', 'Etiquette', 'Master Gunner', 'Mighty Shot', 'Sharpshooter', 
                        'SpecialistWeapon Group (Fencing)', 'Specialist WeaponGroup (Gunpowder)', 'Swashbuckler', 
                        'Trick Riding'],
            'Trappings': ['Pair of Pistols with Powder and Ammunition for 20 Shots', 'Noble’s Garb', 'Hood orMask', 
                          'Riding Horse with Saddle and Harness'],
            'Career Entries': ['Coachman', 'Duellist', 'Estalian Ferryman', 'Minstrel', 'Outlaw', 'Outrider', 
                               'Toll Keeper'],
            'Career Exits': ['Agitator', 'Duellist', 'Master Theif', 'Outlaw Chief', 'Sergeant']},
        'Innkeeper Advance Scheme': {
            'Statblock': [10, 5, 5, 10, 20, 10, 10, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Blather or Lip Reading', 'Charm', 'Common Knowledge (the Empire)', 'Consume Evaluate', 
                       'Gossip', 'Haggle', 'Perception', 'Read/Write or Sleight of Hand', 
                       'Speak Language ( Kislevian, Reikspiel or Tilean)', 'Trade (Cook)'],
            'Talents': ['Etiquette or Streetwise', 'Dealmaker or Street Fighting', 'Strike to Stun'],
            'Trappings': ['Inn', '1 or more Servants'],
            'Career Entries': ['Burgher', 'Servant'],
            'Career Exits': ['Burgher', 'Fence', 'Merchant', 'Outlaw', 'Smuggle']},
        'Interrogator Advance Scheme': {
            'Statblock': [15, 0, 20, 10, 10, 10, 20, 15, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Heal', 'Intimidate', 'Perception', 'Torture'],
            'Talents': ['Menacing', 'Specialist Weapon Group (Flail)', 'Wrestling'],
            'Trappings': ['5 knives', 'Flail', '3 sets of manacles'],
            'Career Entries': ['Barber-Surgeon', 'Bodyguard', 'Jailer', 'Thug'],
            'Career Exits': ['Physician', 'Racketeer', 'Thief']},
        'Journeyman Wizard Advance Scheme': {
            'Statblock': [5, 5, 0, 5, 10, 20, 25, 10, 3, 0, 0, 0, 2, 0, 0],
            'Skills': ['Academic Knowledge (Magic)', 'Academic Knowledge (any one)', 'Channelling', 
                       'Charm or Intimidate', 'Common Knowledge (any two)', 'Magical Sense', 'Read/Write', 
                       'Ride or Swim', 'SpeakArcane Language (Magick)', 'Speak Language(any two)'],
            'Talents': ['Arcane Lore (any one) or Dark Lore (any one)', 'Aethyric Attunementor Dark Magic', 
                        'Fast Hands or Very Resilient', 'Lesser Magic (any two)', 'Meditation or Mighty Missile'],
            'Trappings': ['Grimoire', 'Writing Kit'],
            'Career Entries': ['Apprentice Wizard'],
            'Career Exits': ['Charlatan', 'Master Wizard', 'Scholar']},
        'Judicial Champion Advance Scheme': {
            'Statblock': [35, 0, 15, 15, 20, 10, 15, 0, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Dodge Blow', 'Perception'],
            'Talents': ['Lightning Parry', 'Specialist Weapon Group (Fencing)', 'Specialist Weapon Group (Flail)', 
                        'SpecialistWeapon Group (Parrying)', 'Specialist Weapon Group(Two-handed)'],
            'Trappings': ['Great Weapon', 'Flail or Morning Star', 'Rapier or Foil', 'Buckler or Main Gauche', 
                          '10 Yards of Rope'],
            'Career Entries': ['Sergeant', 'Veteran'],
            'Career Exits': ['Assassin', 'Champion', 'Sergeant', 'Witch Hunter', 'Zealot']},
        'Knight Advance Scheme': {
            'Statblock': [25, 0, 15, 15, 15, 5, 15, 5, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Genealogy/Heraldry or Religion)', 'Academic Knowledge (Strategy/Tactics)',
                       'Dodge Blow', 'Perception', 'Ride', 'Secret Language(Battle Tongue)', 
                       'Speak Language (any two)'],
            'Talents': ['Specialist Weapon Group (Cavalry)', 'Specialist Weapon Group (Flail)', 
                        'Specialist Weapon Group(Two-handed)', 'Strike Mighty Blow'],
            'Trappings': ['Flail or Morning Star', 'Lance', 'Heavy Armour (Full Plate Armour)', 'Shield', 
                          'Religious Symbol', '25 Destrier with Saddle and Harness'],
            'Career Entries': ['Noble Lord', 'Pistolier', 'Sergeant', 'Vampire Hunter'],
            'Career Exits': ['Captain', 'Initiate', 'Knight of the Inner Noble Lord', 'Vampire Hunter']},
        'Knight of the Inner Circle Advance Scheme': {
            'Statblock': [35, 10, 20, 20, 20, 15, 25, 15, 8, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Genealogy/Heraldry or Religion)', 'Academic Knowledge (Strategy/Tactics)', 
                       'Animal Training', 'Charm', 'Command', 'CommonKnowledge (any three)', 'Dodge Blow', 'Perception',
                       'Read/Write', 'Ride', 'Secret Language (Battle Tongue)', 'SecretSigns (Scout or Templar)', 
                       'Speak Language ( Estalian', 'Kislevian', 'or Tilean)'],
            'Talents': ['Etiquette', 'Lightning Parry', 'Seasoned Specialist Weapon Group (Fencing)', 
                        'Specialist Weapon Group (Parrying)', 'Stout-hearted', 'Strike to Strike to Stun'],
            'Trappings': ['Buckler or Main Gauche', 'Rapier or Heavy Armour (Best Craftsmanship Full Plate Armour)',
                          'Religious Symbol', '50 gc'],
            'Career Entries': ['Knight', 'Witch Hunter'],
            'Career Exits': ['Captain', 'Champion', 'Noble Lord', 'Witch Hunter']},
        'Master Thief Advance Scheme': {
            'Statblock': [20, 20, 10, 10, 40, 25, 20, 25, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Concealment', 'Disguise', 'Dodge Blow', 'Evaluate', 'Gamble or Lip Reading', 'Gossip',
                       'Perception', 'Pick Lock', 'Read/ Scale Sheer Surface', 'Secret Language (Thieves’ Tongue)', 
                       'SecretSigns (Thief)', 'Search', 'Silent Move', 'Sleight of Hand', 'Swim'],
            'Talents': ['Specialist Weapon Group (Crossbow)', 'Specialist Weapon Group (Throwing)', 
                        'Street Fighting or Streetwise', 'Trapfinder'],
            'Trappings': ['Crossbow Pistol with 10 Bolts', '2 Throwing Axes/ Hammer or 3 Throwing Daggers/Stars', 
                          'Best Craftsmanship Lock Picks', 'Cloak', 'Sack', 'Best Craftsmanship Rope (10 Yards)'],
            'Career Entries': ['Cat Burglar', 'Crime Lord', 'Highwayman', 'Racketeer', 'Spy'],
            'Career Exits': ['Crime Lord', 'Explorer', 'Outlaw', 'Targeteer']},
        'Master Wizard Advance Scheme': {
            'Statblock': [10, 10, 0, 10, 15, 30, 35, 15, '=4', 0, 0, 0, 3, 0, 0],
            'Skills': ['Academic Knowledge (Magic)', 'Academic Knowledge (any two)', 'Channelling', 
                       'Charm or Common Knowledge (any two)', 'Gossip or Magical Sense', 'Read/Write', 
                       'Speak Arcane Language(Magick)', 'Speak Arcane Language (Daemonic orArcane Elf)', 
                       'Speak Language (any three)'],
            'Talents': ['Aethyric Attunement or Meditation', 'Dark Magic or Strong-minded', 
                        'Fast Hands or Mighty Missile', 'Lesser Magic (any two)'],
            'Trappings': ['Trade Tools (Apothecary)', 'Two magic items'],
            'Career Entries': ['Journeyman Wizard'],
            'Career Exits': ['Explorer', 'Scholar', 'Wizard Lord']},
        'Mate Advance Scheme': {
            'Statblock': [15, 15, 10, 15, 10, 10, 10, 10, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Command', 'Common Knowledge (any two)', 'Consume Alcohol', 'Dodge Blow', 'Gamble', 'Gossip', 
                       'Row', 'Sail', 'Speak Language (Breton', 'Kislevian', 'orNorse)', 'Swim', 'Trade (Shipwright)'],
            'Talents': ['Resistance to Disease', 'Seasoned Traveller', 'Street Fighting'],
            'Trappings': ['Light Armour (Leather Jack)'],
            'Career Entries': ['Marine', 'Seaman'],
            'Career Exits': ['Explorer', 'Merchant', 'Navigator', 'Sea Captain']},
        'Merchant Advance Scheme': {
            'Statblock': [10, 10, 5, 5, 10, 25, 20, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Common Knowledge (any two)', 'Evaluate', 'Gossip', 'Haggle', 'Read/Write', 'Ride', 
                       'Secret Language (Guild Tongue)', 'Speak Language ( Estalian', 'Kislevian', 'or Norse)', 
                       'Speak Language(Reikspiel)', 'Trade (Merchant)'],
            'Talents': ['Dealmaker or Streetwise', 'Super Numerate'],
            'Trappings': ['Town House', 'Warehouse', '1,,000 gc in coin or trade goods'],
            'Career Entries': ['Artisan', 'Burgher', 'Captain', 'Envoy', 'Fisherman', 'Innkeeper', 'Mate', 'Scholar', 
                               'Tradesman'],
            'Career Exits': ['Guild Master', 'Militiaman', 'Racketeer', 'Spy']},
        'Minstrel Advance Scheme': {
            'Statblock': [10, 10, 0, 0, 15, 10, 5, 25, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Common Knowledge (any two)', 'Perception', 'Performer (Musician)', 
                       'Performer (Singer)', 'Read/Write', 'Speak Language (Breton', 'Eltharin or Tilean)'],
            'Talents': ['Etiquette', 'Pubic Speaking'],
            'Trappings': ['Entertainer’s Garb', 'Musical Instrument (Lute or Mandolin)'],
            'Career Entries': ['Entertainer'],
            'Career Exits': ['Charlatan', 'Demagogue', 'Highwayman', 'Student']},
        'Navigator Advance Scheme': {
            'Statblock': [10, 10, 5, 5, 10, 25, 10, 5, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Astronomy)', 'Common Knowledge (any two)', 'Navigation', 'Perception', 
                       'Read/Write', 'Speak Language (Classical)', 'Swim', 'Trade(Cartographer)'],
            'Talents': ['Orientation'],
            'Trappings': ['6 Maps and Charts, Trade Tools (Navigator’s Instruments)'],
            'Career Entries': ['Boatman', 'Fisherman', 'Mate', 'Scribe', 'Seaman'],
            'Career Exits': ['Artisan', 'Explorer', 'Scholar', 'Sea Captain']},
        'Noble Lord Advance Scheme': {
            'Statblock': [25, 15, 10, 10, 10, 20, 20, 30, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (History or Strategy/Tactics)', 'Academic Knowledge (Genealogy/Heraldry)', 
                       'Command', 'Common Knowledge (the Empire)', 'Gossip', 'Perception', 'Read/Write', 'Ride',
                       'Speak Language (Classical)', 'Speak Language (Reikspiel)'],
            'Talents': ['Master Orator', 'Public Speaking', 'Specialist Weapon Group (Fencing)'],
            'Trappings': ['Best Craftsmanship Rapier or Foil', 'Best Craftsmanship Noble’s Garb', '500gc',
                          'Jewellery worth 500gc', 'Destrier with Saddle and Harness'],
            'Career Entries': ['Courtier', 'Knight', 'Knight of the Inner Politician', 'Sea Captain'],
            'Career Exits': ['Captain', 'Knight', 'Scholar', 'Sea Captain']},
        'Outlaw Chief Advance Scheme': {
            'Statblock': [20, 30, 10, 20, 10, 10, 10, 20, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Strategy/Tactics)', 'Common Knowledge (the Empire)', 'Concealment', 
                       'Follow Trail', 'Perception', 'Ride', 'Scale Sheer Surface', 'SecretLanguage (Battle Tongue)', 
                       'Secret Language (Thieves’Tongue)', 'Secret Signs (Scout or Thief)', 'Silent Move'],
            'Talents': ['Lightning Parry', 'Mighty Shot', 'Quick Draw', 'Rapid Reload', 'Sure Shot'],
            'Trappings': ['Bow or Crossbow with 10 arrows or Bolts', 
                          'Medium Armour (Sleeved Mail Shirt and Leather Jack)', 'Horse with Saddle and Harness',
                          'Band of Outlaws'],
            'Career Entries': ['Crime Lord', 'Demagogue', 'Ghost Highwayman', 'Master Thief', 'Racketeer', 'Scout', 
                               'Veteran'],
            'Career Exits': ['Assassin', 'Captain', 'Crime Lord', 'Demagogue']},
        'Physician Advance Scheme': {
            'Statblock': [0, 0, 10, 10, 15, 30, 20, 15, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Science)', 'Heal', 'Perception', 'Prepare Poison', 'Read/Write', 
                       'Speak Language (Classical)', 'Trade (Apothecary)'],
            'Talents': ['Resistance to Disease', 'Strike to Stun', 'Surgery'],
            'Trappings': ['4 Healing Draughts, Trade Tools (Medical Instruments)'],
            'Career Entries': ['Barber-Surgeon', 'Interrogator', 'Student'],
            'Career Exits': ['Friar', 'Guild Master', 'Scholar', 'Spy']},
        'Pistolier Advance Scheme': {
            'Statblock': [20, 20, 10, 10, 15, 0, 15, 15, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Dodge Evaluate or Gossip', 'Perception', 'Secret Signs (Scout)'],
            'Talents': ['Master Gunner', 'Quick Draw', 'Rapid Reload', 'Sharpshooter', 
                        'Specialist WeaponGroup (Gunpowder)', 'Mighty Shot', 'SureShot'],
            'Trappings': ['Pair of Pistols with Ammunition and Gunpowder for 20 Shots', 'Best CraftsmanshipClothing',
                          'Light Warhorse'],
            'Career Entries': ['Engineer', 'Noble'],
            'Career Exits': ['Courtier', 'Duellist', 'Knight', 'Veteran']},
        'Politician Advance Scheme': {
            'Statblock': [5, 5, 5, 10, 0, 20, 10, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (History or Genealogy/Heraldry)', 'Academic Knowledge (Law)', 'Blather', 
                       'Charm', 'Common Knowledge (the Empire)', 'Evaluate', 'Haggle', 'Perception', 
                       'Performer (Actor)', 'Read/ Speak Language (Reikspiel)'],
            'Talents': ['Dealmaker or r', 'Etiquette or Streetwise', 'Master Orator', 'Public Speaking'],
            'Trappings': ['Best Craftsmanship Hand Weapon', 'Best Craftsmanship Leather Jack', 'Pamphlets'],
            'Career Entries': ['Agitator', 'Bailiff', 'Captain', 'Charlatan', 'Crime Lord', 'Demagogue', 'Guild Master',
                               'Herald', 'High Priest', 'Merchant', 'Noble', 'Peasant', 'Racketeer', 'Toll Keeper'],
            'Career Exits': ['Courtier', 'Crime Lord', 'Demagogue', 'Noble Racketeer', 'Steward']},
        'Priest Advance Scheme': {
            'Statblock': [10, 10, 5, 10, 5, 10, 20, 15, 4, 0, 0, 0, 1, 0, 0],
            'Skills': ['Academic Knowledge (any one)', 'Academic Knowledge (Theology)', 'Channelling', 
                       'Common Knowledge (any two)', 'Gossip', 'Magical Sense', 'Perception', 'Read/Write', 
                       'Ride orSwim', 'Speak Arcane Language (Magick)', 'SpeakLanguage (any two)'],
            'Talents': ['Armoured Caster or Master Orator', 'Petty Magic(Divine)',
                        'Strike to Injure or Strike to Stun'],
            'Trappings': ['Prayer Book', 'Writing Kit'],
            'Career Entries': ['Flagellant', 'Friar', 'Initiate'],
            'Career Exits': ['Anointed Priest', 'Flagellant', 'Steward']},
        'Racketeer Advance Scheme': {
            'Statblock': [20, 15, 15, 10, 10, 0, 15, 10, 5, 0, 0, 0, 0, 0, 0],
            'Skills': ['Command', 'Common Knowledge (the Empire)', 'Dodge Blow', 'Evaluate', 'Gossip', 'Haggle',
                       'Perception', 'Shadowing'],
            'Talents': ['Menacing', 'Street Fighting', 'Streetwise', 'Strike Mighty Blow', 'Strike to Stun'],
            'Trappings': ['Knuckle-dusters', 'Good Quality Clothing', 'Hat'],
            'Career Entries': ['Bailiff', 'Bodyguard', 'Cat Burglar', 'Guild Master', 'Interrogator', 'Merchant', 
                               'Protagonist', 'Spy', 'Thug'],
            'Career Exits': ['Fence', 'Master Thief', 'Politician', 'Outlaw Chief']},
        'Scholar Advance Scheme': {
            'Statblock': [5, 5, 5, 5, 10, 30, 15, 15, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (any three)', 'Common Knowledge (any three)', 
                       'Evaluate or Trade (Cartographer)', 'Perception', 'Read/Write', 'SpeakLanguage (any three)',
                       'Speak Language (Classical)'],
            'Talents': ['Linguistics'],
            'Trappings': ['Writing Kit'],
            'Career Entries': ['Anointed Priest', 'Apprentice Friar', 'High Priest', 'Journeyman Wizard', 
                               'Master Wizard', 'Navigator', 'Noble Lord', 'Physician', 'Scribe', 'Sea Captain',
                               'Student'],
            'Career Exits': ['Apprentice Wizard', 'Explorer', 'Merchant', 'Physician', 'Steward']},
        'Scout Advance Scheme': {
            'Statblock': [20, 20, 10, 10, 15, 20, 15, 0, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Animal Care', 'Common Knowledge (any two)', 'Concealment', 'Dodge Blow', 'Follow Trail', 
                       'Perception', 'Ride', 'Secret Language (Ranger Tongue)', 'Secret Signs (Scout)', 'Silent Move', 
                       'Speak Language (any two)'],
            'Talents': ['Charm Animal', 'Mighty Shot or Sure Shot', 'Rapid Reload', 
                        'Specialist Weapon (Crossbow or Longbow)'],
            'Trappings': ['Medium Armour (Mail Shirt and Leather Jack)', 'Shield', '10 Yards of Rope', 
                          'Horse with Saddle and Harness'],
            'Career Entries': ['Bounty Hunter', 'Champion', 'Charcoal- Coachman', 'Fieldwarden', 'Hunter', 
                               'Kithband Messenger', 'Miner', 'Outrider', 'Roadwarden', 'Vagabond', 'Woodsman'],
            'Career Exits': ['Explorer', 'Outlaw Chief', 'Sergeant', 'Vampire Hunter', 'Ghost Strider']},
        'Sea Captain Advance Scheme': {
            'Statblock': [25, 20, 15, 20, 20, 20, 25, 30, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Strategy/Tactics)', 'Animal Training', 'Command', 
                       'Common Knowledge (anythree)', 'Dodge Blow', 'Perception', 'Sail', 'SpeakLanguage (any three)',
                       'Swim', 'Trade (Cartographer orShipwright)'],
            'Talents': ['Disarm', 'Lightning Parry or Seasoned Traveller', 'Specialist Weapon Group (Fencing)', 
                        'Strike Mighty Blow'],
            'Trappings': ['Rapier', 'Light Armour (Leather Jack)', 'Ship'],
            'Career Entries': ['Explorer', 'Mate', 'Navigator', 'Noble Lord'],
            'Career Exits': ['Explorer', 'Noble Lord', 'Scholar', 'Spy']},
        'Sergeant Advance Scheme': {
            'Statblock': [20, 15, 10, 10, 10, 10, 10, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Strategy/Tactics)', 'Common Knowledge (any two)', 'Dodge Blow', 
                       'Intimidate', 'Perception', 'Ride or Swim', 'Secret Language (Battle Tongue)', 
                       'Speak Language (Tilean)'],
            'Talents': ['Menacing or Seasoned Traveller', 'Street Fighting or Wrestling', 'Strike Mighty Blow', 
                        'Strike to Stun'],
            'Trappings': ['Medium Armour (Full Mail Armour)', 'Shield'],
            'Career Entries': ['Assassin', 'Champion', 'Duellist', 'Judicial Champion', 'Kislevite Kossar', 'Marine',
                               'Militiaman', 'Norse Berserker', 'Pistolier', 'Scout', 'Shieldbreaker', 'Soldier',
                               'Squire', 'Targeteer', 'Watchman'],
            'Career Exits': ['Captain', 'Duellist', 'Judicial Champion', 'Knight']},
        'Spy Advance Scheme': {
            'Statblock': [15, 15, 5, 10, 20, 20, 35, 20, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Charm', 'Common Knowledge (any two)', 'Disguise', 'Gossip', 'Lip Reading', 'Performer (Actor)',
                       'Pick Lock', 'Shadowing', 'Sleight of Hand', 'Secret Language (any one)', 'Silent Move',
                       'Speak Language (anythree)'],
            'Talents': ['Flee!', 'Linguistics', 'r', 'Suave or Sixth Sense'],
            'Trappings': ['Disguise Kit', '4 Homing Pigeons'],
            'Career Entries': ['Camp Follower', 'Charlatan', 'Explorer', 'Merchant', 'Minstrel', 'Physician', 
                               'Sea Servant'],
            'Career Exits': ['Assassin', 'Explorer', 'Master Thief', 'Racketeer']},
        'Steward Advance Scheme': {
            'Statblock': [10, 10, 10, 10, 0, 30, 20, 25, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Law)', 'Charm', 'Common Knowledge (the Empire)', 'Evaluate', 'Haggle', 
                       'Intimidate', 'Perception', 'Read/Write', 'Search', 'Speak Language (Reikspiel)', 
                       'Trade (Merchant)'],
            'Talents': ['Public Speaking', 'Super Numerate'],
            'Trappings': ['2 Sets of Best Craftsmanship Noble’s Writing Kit'],
            'Career Entries': ['Courtier', 'Politician', 'Priest', 'Scholar', 'Valet'],
            'Career Exits': ['Crime Lord', 'Fence', 'Merchant', 'Noble']},
        'Targeteer Advance Scheme': {
            'Statblock': [0, 35, 10, 10, 25, 10, 20, 15, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Empire)', 'Gossip', 'Outdoor Survival', 'Perception', 'Search',
                       'Sleight of Hand'],
            'Talents': ['Mighty Shot', 'Rapid Reload', 'Sharpshooter', 'Specialist Weapon Group (Longbow)',
                        'Specialist Weapon Group(Crossbow or Throwing)', 'Sure Shot'],
            'Trappings': ['Longbow or Crossbow with 10 arrows or Light Armour (Leather Jack)'],
            'Career Entries': ['Bounty Hunter', 'Hunter', 'Ghost Strider', 'Master Thief', 'Vampire Hunter', 'Veteran'],
            'Career Exits': ['Assassin', 'Champion', 'Duellist', 'Sergeant']},
        'Vampire Hunter Advance Scheme': {
            'Statblock': [20, 20, 10, 20, 15, 15, 20, 0, 4, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (History or Necromancy)', 'Common Knowledge (the Empire)', 'Concealment',
                       'Dodge Blow', 'Follow Trail', 'Perception', 'Scale Sheer Shadowing', 'Search', 'Silent Move', 
                       'Speak Language(Classical)'],
            'Talents': ['Mighty Shot or Rapid Reload', 'Specialist Weapon Group (Crossbow)', 'Stout-hearted', 
                        'Strike Mighty Strike to Injure', 'Tunnel Rat'],
            'Trappings': ['Repeater Crossbow with 10 Bolts', 'Medium Armour (Full Mail Armour)', 'Blessed Water', 
                          '4 Stakes'],
            'Career Entries': ['Bounty Hunter', 'Field Warden', 'Ghost Strider', 'Knight', 'Scout', 'Tomb Robber'],
            'Career Exits': ['Demagogue', 'Initiate', 'Knight', 'Targeteer', 'Witch Hunter']},
        'Veteran Advance Scheme': {
            'Statblock': [20, 20, 10, 10, 15, 0, 15, 0, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Common Knowledge (the Empire)', 'Consume Dodge Blow', 'Gamble', 'Gossip', 'Intimidate', 
                       'Secret Language (Battle Tongue)'],
            'Talents': ['Mighty Shot or Strike Mighty Blow', 'Rapid Reload or Strike to Injure', 
                        'Specialist Weapon Group (anytwo)', 'Very Resilient or Very Strong'],
            'Trappings': ['Any two weapons', 'Medium Armour(Full Mail Armour)', 'Bottle of Good Craftsmanship Spirits'],
            'Career Entries': ['Flagellant', 'Kislevite Kossar', 'Kithband Warrior', 'Mercenary', 'Norse Berserker',
                               'Pistolier', 'Pit Fighter', 'Runebearer', 'Soldier', 'Squire'],
            'Career Exits': ['Champion', 'Judicial Champion', 'Outlaw', 'Sergeant', 'Targeteer']},
        'Witch Hunter Advance Scheme': {
            'Statblock': [30, 30, 15, 15, 15, 15, 35, 20, 6, 0, 0, 0, 0, 0, 0],
            'Skills': ['Academic Knowledge (Magic)', 'Academic Knowledge (Necromancy)', 'Academic Knowledge (Theology)',
                       'Command', 'Common Knowledge (the Empire)', 'Intimidate', 'Perception', 'Ride', 'Search',
                       'Silent Move', 'SpeakLanguage (any one)'],
            'Talents': ['Lightning Parry', 'Lightning Reflexes or Marksman', 'Public Speaking', 'Sixth Sense', 
                        'Specialist Weapon Group (Crossbow)', 'Specialist Weapon Group (Entangling)', 
                        'SpecialistWeapon Group (Throwing)', 'Stout-hearted', 'Strike Mighty Blow'],
            'Trappings': ['Crossbow Pistol with 10 bolts', 'Best Craftsmanship Hand Weapon', '4 Throwing Knives/Stars', 
                          'Heavy Armour (Full PlateArmour)', '10 Yards of Rope'],
            'Career Entries': ['Anointed Priest', 'Assassin', 'Champion', 'High Judicial Champion', 
                               'Knight of the Inner Circle', 'Vampire Hunter'],
            'Career Exits': ['Captain', 'Champion', 'Demagogue', 'Initiate', 'Knight of the Inner Circle']},
        'Wizard Lord Advance Scheme': {
            'Statblock': [15, 15, 5, 15, 20, 35, 40, 20, 5, 0, 0, 0, 4, 0, 0],
            'Skills': ['Academic Knowledge (Magic)', 'Academic Knowledge (any three)', 'Channelling', 
                       'Charm or Intimidate', 'CommonKnowledge (any three)', 'Magical Sense', 'Read/Write', 
                       'Speak Arcane Language (Magick)', 'Speak Arcane Language(Daemonic or Arcane Elf)', 
                       'Speak Language (any four)'],
            'Talents': ['Aethyric Attunement or Mighty Missile', 'Dark Magic or Meditation', 'Fast Hands or Hardy', 
                        'Lesser Magic (any two)'],
            'Trappings': ['Three magic items', '12 Grimoires'],
            'Career Entries': ['Master Wizard'],
            'Career Exits': ['Explorer', 'Guild Master']},
    }

    return (career_dict[career_name])


if __name__ == '__main__':

    career_selection




