# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WFRP 2e.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import genchar
import guiButtons

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 861)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 391, 141))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.txtName = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txtName.setGeometry(QtCore.QRect(60, 20, 320, 21))
        self.txtName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtName.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtName.setPlainText("")
        self.txtName.setObjectName("txtName")
        self.txtRace = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txtRace.setGeometry(QtCore.QRect(60, 50, 320, 21))
        self.txtRace.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtRace.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtRace.setPlainText("")
        self.txtRace.setObjectName("txtRace")
        self.txtCCareer = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txtCCareer.setGeometry(QtCore.QRect(90, 80, 290, 21))
        self.txtCCareer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCCareer.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCCareer.setPlainText("")
        self.txtCCareer.setObjectName("txtCCareer")
        self.txtPCareer = QtWidgets.QPlainTextEdit(self.groupBox)
        self.txtPCareer.setGeometry(QtCore.QRect(90, 110, 290, 21))
        self.txtPCareer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtPCareer.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtPCareer.setPlainText("")
        self.txtPCareer.setObjectName("txtPCareer")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 140, 391, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 47, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 47, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.txtAge = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtAge.setGeometry(QtCore.QRect(60, 20, 131, 21))
        self.txtAge.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAge.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAge.setPlainText("")
        self.txtAge.setObjectName("txtAge")
        self.txtEyeColor = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtEyeColor.setGeometry(QtCore.QRect(60, 50, 131, 21))
        self.txtEyeColor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtEyeColor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtEyeColor.setPlainText("")
        self.txtEyeColor.setObjectName("txtEyeColor")
        self.txtHaircolor = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtHaircolor.setGeometry(QtCore.QRect(60, 80, 131, 21))
        self.txtHaircolor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtHaircolor.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtHaircolor.setPlainText("")
        self.txtHaircolor.setObjectName("txtHaircolor")
        self.txtStarSign = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtStarSign.setGeometry(QtCore.QRect(60, 110, 130, 21))
        self.txtStarSign.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtStarSign.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtStarSign.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtStarSign.setPlainText("")
        self.txtStarSign.setObjectName("txtStarSign")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 140, 81, 21))
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 101, 21))
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(210, 50, 47, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(210, 110, 91, 21))
        self.label_12.setScaledContents(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(210, 20, 47, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(210, 80, 41, 21))
        self.label_14.setObjectName("label_14")
        self.txtHeight = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtHeight.setGeometry(QtCore.QRect(260, 80, 121, 21))
        self.txtHeight.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtHeight.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtHeight.setPlainText("")
        self.txtHeight.setObjectName("txtHeight")
        self.txtNoofSib = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtNoofSib.setGeometry(QtCore.QRect(310, 110, 71, 21))
        self.txtNoofSib.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtNoofSib.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtNoofSib.setPlainText("")
        self.txtNoofSib.setObjectName("txtNoofSib")
        self.txtWeight = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtWeight.setGeometry(QtCore.QRect(260, 50, 121, 21))
        self.txtWeight.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtWeight.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtWeight.setPlainText("")
        self.txtWeight.setObjectName("txtWeight")
        self.txtGender = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtGender.setGeometry(QtCore.QRect(260, 20, 121, 21))
        self.txtGender.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtGender.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtGender.setPlainText("")
        self.txtGender.setObjectName("txtGender")
        self.txtBirthplace = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtBirthplace.setGeometry(QtCore.QRect(60, 140, 321, 21))
        self.txtBirthplace.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtBirthplace.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtBirthplace.setPlainText("")
        self.txtBirthplace.setObjectName("txtBirthplace")
        self.txtDMarks = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txtDMarks.setGeometry(QtCore.QRect(110, 170, 271, 21))
        self.txtDMarks.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtDMarks.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtDMarks.setPlainText("")
        self.txtDMarks.setObjectName("txtDMarks")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 770, 160, 40))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 340, 391, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(10, 20, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setLineWidth(1)
        self.label_25.setScaledContents(False)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(10, 110, 61, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setLineWidth(1)
        self.label_26.setScaledContents(False)
        self.label_26.setObjectName("label_26")
        self.txtSBS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSBS.setGeometry(QtCore.QRect(110, 40, 31, 21))
        self.txtSBS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSBS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSBS.setPlainText("")
        self.txtSBS.setObjectName("txtSBS")
        self.txtSS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSS.setGeometry(QtCore.QRect(150, 40, 31, 21))
        self.txtSS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSS.setPlainText("")
        self.txtSS.setObjectName("txtSS")
        self.txtST = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtST.setGeometry(QtCore.QRect(190, 40, 31, 21))
        self.txtST.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtST.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtST.setPlainText("")
        self.txtST.setObjectName("txtST")
        self.txtSAg = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSAg.setGeometry(QtCore.QRect(230, 40, 31, 21))
        self.txtSAg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSAg.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSAg.setPlainText("")
        self.txtSAg.setObjectName("txtSAg")
        self.txtSInt = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSInt.setGeometry(QtCore.QRect(270, 40, 31, 21))
        self.txtSInt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSInt.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSInt.setPlainText("")
        self.txtSInt.setObjectName("txtSInt")
        self.txtSWP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSWP.setGeometry(QtCore.QRect(310, 40, 31, 21))
        self.txtSWP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSWP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSWP.setPlainText("")
        self.txtSWP.setObjectName("txtSWP")
        self.txtSFel = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSFel.setGeometry(QtCore.QRect(350, 40, 31, 21))
        self.txtSFel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSFel.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSFel.setPlainText("")
        self.txtSFel.setObjectName("txtSFel")
        self.txtSWS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSWS.setGeometry(QtCore.QRect(70, 40, 31, 21))
        self.txtSWS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSWS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSWS.setPlainText("")
        self.txtSWS.setObjectName("txtSWS")
        self.txtAInt = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAInt.setGeometry(QtCore.QRect(270, 60, 31, 21))
        self.txtAInt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAInt.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAInt.setPlainText("")
        self.txtAInt.setObjectName("txtAInt")
        self.txtAAg = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAAg.setGeometry(QtCore.QRect(230, 60, 31, 21))
        self.txtAAg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAAg.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAAg.setPlainText("")
        self.txtAAg.setObjectName("txtAAg")
        self.txtAWS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAWS.setGeometry(QtCore.QRect(70, 60, 31, 21))
        self.txtAWS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAWS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAWS.setPlainText("")
        self.txtAWS.setObjectName("txtAWS")
        self.txtAFel = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAFel.setGeometry(QtCore.QRect(350, 60, 31, 21))
        self.txtAFel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAFel.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAFel.setPlainText("")
        self.txtAFel.setObjectName("txtAFel")
        self.txtABS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtABS.setGeometry(QtCore.QRect(110, 60, 31, 21))
        self.txtABS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtABS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtABS.setPlainText("")
        self.txtABS.setObjectName("txtABS")
        self.txtAT = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAT.setGeometry(QtCore.QRect(190, 60, 31, 21))
        self.txtAT.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAT.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAT.setPlainText("")
        self.txtAT.setObjectName("txtAT")
        self.txtAS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAS.setGeometry(QtCore.QRect(150, 60, 31, 21))
        self.txtAS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAS.setPlainText("")
        self.txtAS.setObjectName("txtAS")
        self.txtAWP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAWP.setGeometry(QtCore.QRect(310, 60, 31, 21))
        self.txtAWP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAWP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAWP.setPlainText("")
        self.txtAWP.setObjectName("txtAWP")
        self.txtCInt = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCInt.setGeometry(QtCore.QRect(270, 80, 31, 21))
        self.txtCInt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCInt.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCInt.setPlainText("")
        self.txtCInt.setObjectName("txtCInt")
        self.txtCAg = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCAg.setGeometry(QtCore.QRect(230, 80, 31, 21))
        self.txtCAg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCAg.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCAg.setPlainText("")
        self.txtCAg.setObjectName("txtCAg")
        self.txtCWS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCWS.setGeometry(QtCore.QRect(70, 80, 31, 21))
        self.txtCWS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCWS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCWS.setPlainText("")
        self.txtCWS.setObjectName("txtCWS")
        self.txtCFel = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCFel.setGeometry(QtCore.QRect(350, 80, 31, 21))
        self.txtCFel.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCFel.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCFel.setPlainText("")
        self.txtCFel.setObjectName("txtCFel")
        self.txtCBS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCBS.setGeometry(QtCore.QRect(110, 80, 31, 21))
        self.txtCBS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCBS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCBS.setPlainText("")
        self.txtCBS.setObjectName("txtCBS")
        self.txtCT = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCT.setGeometry(QtCore.QRect(190, 80, 31, 21))
        self.txtCT.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCT.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCT.setPlainText("")
        self.txtCT.setObjectName("txtCT")
        self.txtCS = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCS.setGeometry(QtCore.QRect(150, 80, 31, 21))
        self.txtCS.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCS.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCS.setPlainText("")
        self.txtCS.setObjectName("txtCS")
        self.txtCWP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCWP.setGeometry(QtCore.QRect(310, 80, 31, 21))
        self.txtCWP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCWP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCWP.setPlainText("")
        self.txtCWP.setObjectName("txtCWP")
        self.txtSA = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSA.setGeometry(QtCore.QRect(70, 130, 31, 21))
        self.txtSA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSA.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSA.setPlainText("")
        self.txtSA.setObjectName("txtSA")
        self.txtSB = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSB.setGeometry(QtCore.QRect(150, 130, 31, 21))
        self.txtSB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSB.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSB.setPlainText("")
        self.txtSB.setObjectName("txtSB")
        self.txtAIp = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAIp.setGeometry(QtCore.QRect(310, 150, 31, 21))
        self.txtAIp.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAIp.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAIp.setPlainText("")
        self.txtAIp.setObjectName("txtAIp")
        self.txtAA = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAA.setGeometry(QtCore.QRect(70, 150, 31, 21))
        self.txtAA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAA.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAA.setPlainText("")
        self.txtAA.setObjectName("txtAA")
        self.txtSTB = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSTB.setGeometry(QtCore.QRect(190, 130, 31, 21))
        self.txtSTB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSTB.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSTB.setPlainText("")
        self.txtSTB.setObjectName("txtSTB")
        self.txtSIP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSIP.setGeometry(QtCore.QRect(310, 130, 31, 21))
        self.txtSIP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSIP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSIP.setPlainText("")
        self.txtSIP.setObjectName("txtSIP")
        self.txtCTB = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCTB.setGeometry(QtCore.QRect(190, 170, 31, 21))
        self.txtCTB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCTB.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCTB.setPlainText("")
        self.txtCTB.setObjectName("txtCTB")
        self.txtSW = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSW.setGeometry(QtCore.QRect(110, 130, 31, 21))
        self.txtSW.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSW.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSW.setPlainText("")
        self.txtSW.setObjectName("txtSW")
        self.txtAMag = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAMag.setGeometry(QtCore.QRect(270, 150, 31, 21))
        self.txtAMag.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAMag.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAMag.setPlainText("")
        self.txtAMag.setObjectName("txtAMag")
        self.txtAM = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAM.setGeometry(QtCore.QRect(230, 150, 31, 21))
        self.txtAM.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAM.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAM.setPlainText("")
        self.txtAM.setObjectName("txtAM")
        self.txtCA = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCA.setGeometry(QtCore.QRect(70, 170, 31, 21))
        self.txtCA.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCA.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCA.setPlainText("")
        self.txtCA.setObjectName("txtCA")
        self.txtSM = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSM.setGeometry(QtCore.QRect(230, 130, 31, 21))
        self.txtSM.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSM.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSM.setPlainText("")
        self.txtSM.setObjectName("txtSM")
        self.txtCW = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCW.setGeometry(QtCore.QRect(110, 170, 31, 21))
        self.txtCW.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCW.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCW.setPlainText("")
        self.txtCW.setObjectName("txtCW")
        self.txtCMag = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCMag.setGeometry(QtCore.QRect(270, 170, 31, 21))
        self.txtCMag.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCMag.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCMag.setPlainText("")
        self.txtCMag.setObjectName("txtCMag")
        self.txtAW = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAW.setGeometry(QtCore.QRect(110, 150, 31, 21))
        self.txtAW.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAW.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAW.setPlainText("")
        self.txtAW.setObjectName("txtAW")
        self.txtCFP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCFP.setGeometry(QtCore.QRect(350, 170, 31, 21))
        self.txtCFP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCFP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCFP.setPlainText("")
        self.txtCFP.setObjectName("txtCFP")
        self.txtASB = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtASB.setGeometry(QtCore.QRect(150, 150, 31, 21))
        self.txtASB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtASB.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtASB.setPlainText("")
        self.txtASB.setObjectName("txtASB")
        self.txtCIP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCIP.setGeometry(QtCore.QRect(310, 170, 31, 21))
        self.txtCIP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCIP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCIP.setPlainText("")
        self.txtCIP.setObjectName("txtCIP")
        self.txtCSB = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCSB.setGeometry(QtCore.QRect(150, 170, 31, 21))
        self.txtCSB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCSB.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCSB.setPlainText("")
        self.txtCSB.setObjectName("txtCSB")
        self.txtSFP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSFP.setGeometry(QtCore.QRect(350, 130, 31, 21))
        self.txtSFP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSFP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSFP.setPlainText("")
        self.txtSFP.setObjectName("txtSFP")
        self.txtATB = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtATB.setGeometry(QtCore.QRect(190, 150, 31, 21))
        self.txtATB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtATB.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtATB.setPlainText("")
        self.txtATB.setObjectName("txtATB")
        self.txtCM = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtCM.setGeometry(QtCore.QRect(230, 170, 31, 21))
        self.txtCM.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtCM.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtCM.setPlainText("")
        self.txtCM.setObjectName("txtCM")
        self.txtAFP = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtAFP.setGeometry(QtCore.QRect(350, 150, 31, 21))
        self.txtAFP.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtAFP.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtAFP.setPlainText("")
        self.txtAFP.setObjectName("txtAFP")
        self.txtSMag = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSMag.setGeometry(QtCore.QRect(270, 130, 31, 21))
        self.txtSMag.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtSMag.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.txtSMag.setPlainText("")
        self.txtSMag.setObjectName("txtSMag")
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(70, 20, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setLineWidth(1)
        self.label_27.setScaledContents(False)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(110, 20, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setLineWidth(1)
        self.label_28.setScaledContents(False)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(150, 20, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setLineWidth(1)
        self.label_29.setScaledContents(False)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(270, 20, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setLineWidth(1)
        self.label_30.setScaledContents(False)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setGeometry(QtCore.QRect(310, 20, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setLineWidth(1)
        self.label_31.setScaledContents(False)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setGeometry(QtCore.QRect(350, 20, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setLineWidth(1)
        self.label_32.setScaledContents(False)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(190, 20, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setLineWidth(1)
        self.label_33.setScaledContents(False)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(230, 20, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)
        self.label_35.setLineWidth(1)
        self.label_35.setScaledContents(False)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(20, 40, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setLineWidth(1)
        self.label_34.setScaledContents(False)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.groupBox_3)
        self.label_36.setGeometry(QtCore.QRect(20, 60, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setLineWidth(1)
        self.label_36.setScaledContents(False)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.groupBox_3)
        self.label_37.setGeometry(QtCore.QRect(20, 80, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setLineWidth(1)
        self.label_37.setScaledContents(False)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(20, 170, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setLineWidth(1)
        self.label_38.setScaledContents(False)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_3)
        self.label_39.setGeometry(QtCore.QRect(20, 150, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        self.label_39.setLineWidth(1)
        self.label_39.setScaledContents(False)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_3)
        self.label_40.setGeometry(QtCore.QRect(20, 130, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setLineWidth(1)
        self.label_40.setScaledContents(False)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_3)
        self.label_41.setGeometry(QtCore.QRect(70, 110, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        self.label_41.setLineWidth(1)
        self.label_41.setScaledContents(False)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setGeometry(QtCore.QRect(350, 110, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setLineWidth(1)
        self.label_42.setScaledContents(False)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_3)
        self.label_43.setGeometry(QtCore.QRect(230, 110, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setLineWidth(1)
        self.label_43.setScaledContents(False)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_3)
        self.label_44.setGeometry(QtCore.QRect(150, 110, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setLineWidth(1)
        self.label_44.setScaledContents(False)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_3)
        self.label_45.setGeometry(QtCore.QRect(270, 110, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        self.label_45.setLineWidth(1)
        self.label_45.setScaledContents(False)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setGeometry(QtCore.QRect(310, 110, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        self.label_46.setLineWidth(1)
        self.label_46.setScaledContents(False)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setGeometry(QtCore.QRect(110, 110, 31, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        self.label_47.setLineWidth(1)
        self.label_47.setScaledContents(False)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_3)
        self.label_48.setGeometry(QtCore.QRect(190, 110, 30, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setLineWidth(1)
        self.label_48.setScaledContents(False)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 770, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 540, 390, 130))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 370, 100))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 670, 390, 90))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(100, 40, 47, 13))
        self.label_15.setObjectName("label_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.Stretch)
        self.pushButton.clicked.connect(self.exitbutton)
        # self.pushButton_2.clicked.connect(self.generate_character)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Character"))
        self.label.setText(_translate("MainWindow", "Name"))
        self.label_2.setText(_translate("MainWindow", "Race"))
        self.label_3.setText(_translate("MainWindow", "Current Career"))
        self.label_4.setText(_translate("MainWindow", "Previous Career"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Personal Details"))
        self.label_5.setText(_translate("MainWindow", "Age"))
        self.label_6.setText(_translate("MainWindow", "Eye Color"))
        self.label_7.setText(_translate("MainWindow", "Hair Color"))
        self.label_8.setText(_translate("MainWindow", "Star Sign"))
        self.label_9.setText(_translate("MainWindow", "Birthplace"))
        self.label_10.setText(_translate("MainWindow", "Distinguishing Marks"))
        self.label_11.setText(_translate("MainWindow", "Weight"))
        self.label_12.setText(_translate("MainWindow", "Number of Siblings"))
        self.label_13.setText(_translate("MainWindow", "Gender"))
        self.label_14.setText(_translate("MainWindow", "Height"))
        self.pushButton.setText(_translate("MainWindow", "Fake exit button here"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Character Profile"))
        self.label_25.setText(_translate("MainWindow", "Main"))
        self.label_26.setText(_translate("MainWindow", "Secondary"))
        self.label_27.setText(_translate("MainWindow", "WS"))
        self.label_28.setText(_translate("MainWindow", "BS"))
        self.label_29.setText(_translate("MainWindow", "S"))
        self.label_30.setText(_translate("MainWindow", "Int"))
        self.label_31.setText(_translate("MainWindow", "WP"))
        self.label_32.setText(_translate("MainWindow", "Fel"))
        self.label_33.setText(_translate("MainWindow", "T"))
        self.label_35.setText(_translate("MainWindow", "Ag"))
        self.label_34.setText(_translate("MainWindow", "Starting"))
        self.label_36.setText(_translate("MainWindow", "Advance"))
        self.label_37.setText(_translate("MainWindow", "Current"))
        self.label_38.setText(_translate("MainWindow", "Current"))
        self.label_39.setText(_translate("MainWindow", "Advance"))
        self.label_40.setText(_translate("MainWindow", "Starting"))
        self.label_41.setText(_translate("MainWindow", "A"))
        self.label_42.setText(_translate("MainWindow", "FP"))
        self.label_43.setText(_translate("MainWindow", "M"))
        self.label_44.setText(_translate("MainWindow", "SB"))
        self.label_45.setText(_translate("MainWindow", "Mag"))
        self.label_46.setText(_translate("MainWindow", "IP"))
        self.label_47.setText(_translate("MainWindow", "W"))
        self.label_48.setText(_translate("MainWindow", "TB"))
        self.pushButton_2.setText(_translate("MainWindow", "Generate Character"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Weapons"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Enc"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Group"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Damage"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Range"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Reload"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Qualities"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Armor"))
        self.label_15.setText(_translate("MainWindow", "TODO"))

    def exitbutton(self,MainWindow):
        guiButtons.exitbutton()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

